opentx/opentx

radio/src/telemetry/mavlink.cpp

It compiles ok, but I have't tested on a 9XR radio.
Modifications are minimal and it should work

Correction to "compilation error on 9XR with MAVLINK extension"

---

radio/src/gui/view_mavlink.cpp
radio/src/serial.cpp
radio/src/serial.h
radio/src/telemetry/mavlink.cpp
radio/src/telemetry/mavlink.h

I used a trick to avoid compiler warning about 115200 speed.
Tested on my APM2.5 and openlrsng settled @ 115200 and works.
Note: 115200 to 115400 difference is 1.8% -> should be compatible with RS232C standards.

Issue #1935 - added Mavlink 115200 Baud speed - to test

---

radio/src/targets/stock/board_stock.cpp

This fixes #1970.
The functionality of timer0 and timer2 are switched between ATmega64/128
and 641/1281/2561. When compiled for ATmega2561, this commit sets up timer0
in the same way as timer2 on ATmega64/128 (phase correct PWM, clk/64 count
rate, inverted if SP22 is defined).
The previous quick fix had a typo in the initialization of TCCR0B (0b111 is
an invalid value for the clock select bits CS2:0). It also did not respect
the SP22 define which indicates the PWM must be inverted. Smartieparts
v2.2 or later programmer boards have an inverted backlight driver. Finally,
it is unnecessary to set DDB7 as it is already set in boardInit() (line
101).

Tested fix for PWM_BACKLIGHT on ATmega2561 MCUs

---

radio/releasenotes.txt
radio/src/Makefile
radio/src/pulses/ppm_arm.cpp
radio/src/targets/taranis/board_taranis.h
radio/src/targets/taranis/pulses_driver.cpp
radio/src/targets/taranis/trainer_driver.cpp

Removed support for internal module PPM mode (Taranis)
Hw specific code moved to drivers
I have tested this on my Taranis radio and oscilloscope. I measured both external module and trainer port signals before and after this modification. My tests show that it now works correct in every mode. 
**But I won't let this be merged until somebody else also tests this on their radio**.
Another thing: There are already upset/confused users on forums. They are mainly annoyed by the fact that such important thing as PPM polarity has changed in 2.0.15 (fortunately in reality it hasn't changed yet) and they were not aware of that. They say that they were not informed about this at the upgrade time.  We have a note about this in the firmware changelog, but I gues that is not enough for everybody. Do …

Fixes #1937: reverse polarity on external CPPM output (Taranis)

---

companion/src/firmwares/opentx/opentxGruvin9xsimulator.cpp
companion/src/firmwares/opentx/opentxM128simulator.cpp
companion/src/firmwares/opentx/opentxM64simulator.cpp
companion/src/firmwares/opentx/opentxSky9xsimulator.cpp
companion/src/firmwares/opentx/opentxTaranisSimulator.cpp
radio/src/Makefile
radio/src/debug.cpp
radio/src/eeprom_raw.cpp
radio/src/eeprom_rlc.cpp
radio/src/gui/menu_model.cpp
radio/src/gui/view_main.cpp
radio/src/gui/view_statistics.cpp
radio/src/lcd_common.cpp
radio/src/lua.cpp
radio/src/mixer.cpp
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/tests/timers.cpp
radio/src/timers.cpp
radio/src/timers.h

Timers moved to timer.cpp
Added timer overflow protection
Added timer gtests
THt mode now triggers on THR>10%
Timers code was so complex I decided to write a bunch of gtest for them. All timers related code moved to separate file. Unfortunately this move hides real fix of issue #2009, but according to tests it should be fixed now. Please review and test before the merge. We must be careful on `master` branch. If this pull is accepted, I will port it to the `next`.

Fixes #2009: Timer Voice minute call not working for persistent timers

---

companion/src/contributorsdialog.cpp
companion/src/contributorsdialog.ui

I think this is a cool feature when combined with the release notes that contain links to fixed issues.

Changelog links now open in external browser

---

companion/src/cmake/FindXsd.cmake

Just two extra paths to find XSD "All-In-One Package" for people who install it just to compile OpenTX (like me).
Then a simple export XSDDIR=$DIR/xsd-3.3.0+dep/xsd makes cmake find XSD.

Fix #2138 - companion compile error on Slackware linux

---

companion/src/modeledit/setup.cpp

Limit input characters for model name in companion. Use the same rules as for flight mode names.
Allowed characters " A-Za-z0-9_.-," (space included).

Fix to #2122

---

radio/src/translations/cz.h.txt
radio/src/translations/de.h.txt
radio/src/translations/en.h.txt
radio/src/translations/es.h.txt
radio/src/translations/fi.h.txt
radio/src/translations/fr.h.txt
radio/src/translations/it.h.txt
radio/src/translations/pl.h.txt
radio/src/translations/pt.h.txt
radio/src/translations/se.h.txt

The changes in #2129 broke how trim switches render on the 9X, this adds the taranis compile function to render the old tRl style labels on other devices.

Fix trim switch labels on 9X

---

companion/src/companion.cpp
companion/src/simulation/joystick.cpp
companion/src/simulator.cpp
radio/src/simu.cpp
radio/src/targets/simu/simpgmspace.cpp

Now that we use two SDL subsystems (joystick and audio) the SDL initialization has to be corrected. 
This pull might also affect and/or fix https://github.com/opentx/opentx/issues/1732#issuecomment-87364197
If accepted I will prepare a PR for `next` branch.

Proper SDL library initialization for Audio and Joystick subsystems

---

radio/src/Makefile
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/switches.cpp
radio/src/targets/common_avr/adc_driver.cpp
radio/src/targets/common_avr/board_avr.h
radio/src/targets/common_avr/telemetry_driver.cpp
radio/src/targets/gruvin9x/board_gruvin9x.cpp
radio/src/targets/mega2560/board_mega2560.cpp
radio/src/targets/stock/board_stock.cpp
radio/src/targets/stock/board_stock.h

TELEMETRY_MOD=14051 (by gerardv @ forum.turnigy9xr.com) makes USART0 available
by reallocating AIL and THR onto pins 14 and 15 of the 14051 multiplexer.
TELEMETRY_MOD=14051_SWAPPED is based on TELEMETRY_MOD=14051, but uses USART1
instead of USART0, freeing USART0 for other purposes (debugging, interfacing
via AVRISP port). USART1 is freed up by reallocating LVert Trim Dn/Up onto
14051's 12 and 1 pins respectively.
Additionally, this commit cleans a few things up:
* moves AVR ADC-related code to adc_driver.cpp,
* provides #defines to have a convenient way to access either USART0 or USART1
registers depending on static (build-time) configuration
* moves code related to this telemetry mod to board_stock
* replaces a few magic numbers with enums.
Thanks to @bsongis for review and suggestions!

TELEMETRY_MOD=14051_SWAPPED

---

companion/src/modeledit/modeledit.cpp
companion/src/modeledit/telemetry.ui
companion/src/modeledit/telemetry_analog.ui

I have seen fancy resizing of modeledit window when switching from one tab to the other, this is due to the fact that panels have not still updated and so we fix a minimum width that is not the right one.
Updating the panels before adding them, slow down a little bit the opening of the window but avoid problems with resizing.
Also I have modified a little bit telemetry tab to avoid huge distances between labels and fields.

Modeledit fixes

---

companion/src/logsdialog.cpp

Fixes a mostly unnoticeable glitch when loading a second file in Log Viewer.
sessions_CB was cleared too early. If you had something plotted, that means a new plot was done.

[companion][logsdialog]Small glitch when loading a second file.

---

radio/releasenotes.txt
radio/src/targets/taranis/STM32_USB-Host-Device_Lib_V2.1.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_scsi.c

This attempts to fix large (>4GB) SD card problem without resorting to 64 bit variables and arithmetics.
I have tested this with my radio and 8GB SD card and looks like it is working. I insist that somebody else also tests this, before we merge into `master`!
Closes #2154

Fixes #2154: USB mass storage problem with cards bigger than 4GB

---

companion/src/appdata.cpp
companion/src/appdata.h
companion/src/apppreferencesdialog.cpp
companion/src/apppreferencesdialog.ui
companion/src/firmwares/er9x/simulator/er9xsimulator.cpp
companion/src/firmwares/er9x/simulator/er9xsimulator.h
companion/src/firmwares/ersky9x/simulator/ersky9xsimulator.cpp
companion/src/firmwares/ersky9x/simulator/ersky9xsimulator.h
companion/src/firmwares/opentx/simulator/opentxsimulator.cpp
companion/src/firmwares/opentx/simulator/opentxsimulator.h
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatorinterface.h
radio/src/audio_arm.h
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h

Closes #2260 
Had to do some adaptations to the #2344 commits. The profile settings were no longer available in simulator interface. Therefore I changed the interface a little bit to pass on the whole profile to the simulator interface. Some code deduplication also done.
@bsongis  On a related note: it seems that files in https://github.com/opentx/opentx/tree/next/companion/src/firmwares/er9x, https://github.com/opentx/opentx/tree/next/companion/src/firmwares/th9x and several other are obsolete - ie not used anymore. Can they be removed?

Fixes #2260: added volumeGain in simulator (ported from master)

---

radio/src/targets/taranis/adc_driver.cpp

**WARNING** this is completely untested! I have no radio with S3 pot.
Closes #2364 
If accepted I will port it to the `next`

Fixes #2364: use fixed analog value for non-connected pots

---

radio/src/telemetry/telemetry.cpp

I haven't checked if there is any other check that prevents creation of duplicate sensor in gui.

Fixes #2513: set value of duplicated telemetry sensors

---

radio/releasenotes.txt
radio/src/telemetry/frsky_d.cpp

Fixes #2530: VFAS id 0x3A and 0x3B: wrong calculation of value
Closes #2530, closes #2531 
I've only tested #2531 on my setup and its is fixed.
The #2530 issue was **not tested** I don't have that sensor. The formula was taken from 2.0 sources and multiplied by 10.

Fixes #2531: VFAS id 0x39: was 10x to small

---

radio/src/gui/Taranis/menu_model_telemetry.cpp

This fixes problem on the sensor menu.  Closes #2533.
**But other menus** uses the same kind of code and could have the same issue.

Fixes #2533: menu was wrong if all items on the end were hidden

---

radio/src/sbus.cpp

Proposed in issue #2579. When the receiver (at least the X8R & X4R do) goes into failsafe mode, it continues sending SBUS frames with the failsafe bit set. I think we should reject those frames as being an invalid trainer signal, so that the control can return to the instructor.

Added support for SBUS failsafe bit

---

companion/src/simulation/simulatorimport.h
radio/src/Makefile
radio/src/audio_arm.cpp
radio/src/audio_arm.h
radio/src/gui/9X/menu_general_trainer.cpp
radio/src/gui/Taranis/menu_general_trainer.cpp
radio/src/mixer.cpp
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/sbus.cpp
radio/src/targets/sky9x/board_sky9x.cpp
radio/src/targets/taranis/trainer_driver.cpp
radio/src/tests/mixer.cpp
radio/src/trainer_input.cpp
radio/src/trainer_input.h
radio/util/tts.py

- added alarm “Trainer signal lost” & “Trainer signal recovered”.
- moved PPM capture code to trainer_input.{h,cpp}
This is the second try (see earlier push request #2593).
(Fixes #2579)

Fixes #2579: Added support for Trainer signal alarm

---

radio/releasenotes.txt
radio/src/telemetry/frsky.h
radio/src/telemetry/frsky_d.cpp

Closes #2607 
Tested in simu with the help of gdb (manually calling function `call processHubPacket(0x39, 14087)`) and it seems to work.

Fixes #2607: Added support for 0.01V resolution to D series VFAS ID 0x39

---

radio/releasenotes.txt
radio/src/gui/Taranis/menu_general_sdmanager.cpp
radio/src/targets/simu/simpgmspace.cpp

Disable menu for [..],
Refresh file list after delete,
Copy destination can be a directory,
Prevent copy/paste into the same directory,
Enabled renaming of directories and files without extension,
Removed delete menu option for directories,
Several simulator filesystem functions improved
Closes #2623 
Please test thoroughly before merging!

Fixes #2623: several fixes:

---

radio/src/gui/menu_general.cpp
radio/src/targets/simu/simpgmspace.cpp

Disable menu for [..],
Refresh file list after delete,
Removed delete menu option for directories,
Several simulator filesystem functions improved
Closes #2623 
This is the the port of #2691 to the 2.0 branch. I urge you to test this thoroughly. There are some changes compared to the 2.1 solution, namely the `REFRESH_FILES()` is different: `m_posVert = 1` where on 2.1 the `m_posVert = 0` is used.

Fixes #2623: several fixes (ported from 2.1):

---

radio/src/lua_api.cpp

Changes to address issue #2780.  Tested on Taranis hardware using two different GPS units and 2-cell and 3-cell lipos with FrSky Lipo voltage sensor.
Note: this change also includes modification of getValue for UNIT_GPS to use table members 'lat' and 'lon' (not capitalized) following the convention of the luaGetDateTime() function.
Due to problems related to variable scope, I opted to comment the initial call to getValue(src) indicating that it is ignored for special telemetry values rather than restructure the use of the variable 'value'.
David

Issue2780 - getValue() for special telemetry fields

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/telemetrysimu.ui
radio/src/telemetry/frsky.cpp

Add ability to select the sensor instance  to which the  telemetry simulator sends data,
Add default data to detected sensors (RSSI, SWR, A1, A2, rxBAT) in Companion Simulator to prevent alarms programmed with LS/SF from alarming constantly while in the simulator.
Fixes issue 2762.

Jtaylor2/issue  2762

---

companion/src/comparedialog.cpp
companion/src/modelprinter.cpp
companion/src/modelprinter.h
companion/src/multimodelprinter.cpp
companion/src/multimodelprinter.h
companion/src/printdialog.cpp

Closes #2896.
Perhaps this change will fix the original issue. The model curves are no longer created on disk, but embedded directly into the document.

Fixes #2896: draw curves without using temporary disk files

---

radio/src/gui/Taranis/lcd.cpp

I tried fixing input parameters to safe values, but the code was too complicated. Instead a simple check is done, if start or end of the line is outside the LCD the drawing is skipped altogether.
This pull probably closes #2925, but we need to verify that.

Fixes #2925: added coordinate check in lcd_line()

---

companion/src/simulation/simulatorinterface.cpp

Remove __CYGWIN__ from Issue 3012 Windows pathing fix because Cygwin uses posix pathing and not Windows pathing and does define __GNUC__ as well as __CYGWIN__..

Remove __CYGWIN__ from Issue 3012 Windows pathing fix because Cygwin

---

companion/src/flasheepromdialog.ui

Updating the backupBeforeWrite toolTip. It was incorrectly set to the checkFirmwareCompatibility text.

Update flasheepromdialog.ui, Fixed backupBeforeWrite toolTip.

---

radio/src/lua/interface.cpp

As scripts are loaded it will check for existing file <file>.lua.src and compile it to <file>.lua if found.
This functionality still requires the build option LUA_COMPILE=YES

Modifications to luaCompileAndSave()

---

radio/src/targets/simu/simpgmspace.cpp

~~Conversion of backward slash to forward slash for companion.~~
Fixes #3025 
Solution was to modify convertSimuPath() to append fully qualified path name for requests starting with both forward and backward slashes.

Issue #3024 - Companion 2.1 (windows) - Lua 'execute' fails in non-root directory

---

radio/src/thirdparty/GCS_MAVLink/include_v1.0/mavlink_helpers.h
radio/src/thirdparty/STM32_USB-Host-Device_Lib_V2.1.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_scsi.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.

Avoid conditional directives that split up parts of statements.

---

radio/src/lua/api_general.cpp

Closes #2921 
I think this is the best way, the flight mode is not available in mixer sources.
Test script:
```lua
local function run(event)
local fmNum, fmName = getFlightMode()
lcd.clear()
lcd.drawText(10, 10, "fm: "..fmNum.." name: '"..fmName.."'")
return 0
end
return { run=run }
```

Fixes #2921: Lua getFlightMode() function added

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/telemetrysimu.ui

Fixes #3147 - telemetry simulator changes to send ASpd as knots in telemetry frame. Simulator input (text box) will be kph.  Added log playback support for logging in knots, kph, or mph.

Changes to send ASpd as knots

---

radio/src/gui/taranis/lcd.cpp

[Compiled and Tested]
Decimal point needed to be shifted one pixel to the left.
This is a correction also appearing in #2666
Same as #3348 but for branch next.

[Taranis] fixed placement of decimal point in SMLSIZE font

---

radio/util/generate_datacopy.py

The clang.index python library does not look in the default path where the library is installed

Fix building OpenTX under OS X

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h
companion/src/logsdialog.ui

Here are some improvement for log viewer that I wanted to have for a long time:
* find and display max altitude
* enable user to position two cursors and calculate time and altitude difference for them 
Cursors are placed with the right mouse key. Second cursor is placed with SHIFT + right button.
The implementation is open for discussion, especially the visible part. I don't particularly like the way I display the results in a simple label. Ideas how to better use the dialog space are welcome.
Here is an example screen:

Log viewer improvements

---

radio/src/pulses/pulses_arm.cpp

Enable DSM protocols on all targets that define DSM2 macro, not just on Taranis.
#3279

Enable DSM protocols on all targets that define DSM2 macro.

---

radio/src/lua/api_lcd.cpp

This fixes  lcd.drawRectangle force close on Horus. This changes also add a new extra mandatory field 'thickness' : doc will need to be updated accordingly
This fixes #3486

Fix lcd.drawRectangle on Horus

---

radio/src/lua/api_lcd.cpp

This enables lcd.drawGauge on Horus also. No usage difference with other platforms. Unsure why it wasn't initialy included, so beware !

Enables lcd.drawGauge on Horus

---

companion/src/modeledit/flightmodes.cpp

Used the GVars logic for the fix.
Only compiled and tested on Ubuntu 14.04

Fixes #3459 Rotary encoders linked flight mode can freeze Companion

---

radio/sdcard/horus/WIDGETS/BattCheck/main.lua

Forget about lowest cell when you change lipo without changing model or turning radio off

Give BattCheck a 'selective' memory

---

companion/src/helpers.cpp

quickfix for issue #3518: GVar combobox not being refreshed when GV checkbox (re-)selected
*added by projectkk2glider:* Closes #3518

Fix GVar display combobox

---

radio/src/CMakeLists.txt

Only tested on my X9D+. It allows me to boot the device into the OpenTX firmware by using 'make flash' (on switch must be on), combined with -DUSB=SERIAL and -DCLI=YES and the reboot command I can test a new firmware on the device without removing/plugging the usb cable

tell dfu-util to boot the device to boot after flashing

---

radio/src/pulses/pulses_arm.h

The second element of the modulePulsesData was never forced to be correctly aligned. Without the new
pulses and without the Multimodule code the second element was never misaligned since the PXX pulses
union member was always the largest member and was 4 byte aligned by coincidence, also making the
second modulePulseData array member 4 byte aligned.
With the Multimodule option enabled the dsm pulses struct becomes the largest union member with 607 bytes
and the second modulePulsesData is not aligned to anything anymore which completely screws up the pulses
generation.
Forcing the alignment of the ModulePulsesData fixes this issue.

Fix alignment bug of pulses data array

---

companion/src/eeprominterface.cpp

Fixes display error in Companion when a trim in a linked flight mode sequence has Own Value

Fixes #3547: Flight modes linked trims display value error

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/modeledit/flightmodes.cpp
radio/src/opentx.cpp

Fixes #3473 Companion initialise global variables and rotary encoders to linked to Flight mode 0.
Companion trims disabled when linked to other flight mode except when + own as offset.
Radio initialise rotary encoders linked to Flight mode 0.

Fixed #3473: New model global variables and rotary encoders initialisation and trim controls behaviour

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/modeledit/flightmodes.cpp

Fixes #3472 Circular linked global variables.
Fixes circular linked rotary encoders.
Warn user when creating circular links.
Move rotary encoder code to ModelData class for consistency with global variables.

Fixes 3472: circular linked global variables and rotary encoders in Companion

---

radio/src/lua/api_lcd.cpp

Scale is like in % (50 divides by two, 200 doubles)
Default scale to 0 to allow DMA in target function (thx Bertrand)

Add scale to lcd.drawBitmap. 

---

radio/src/targets/taranis/flash_driver.cpp

The order preference in flash_driver would evaluate ! before & but I think checking the bit first is what was intended

Fix gcc 5.4 compiler warnings

---

radio/src/gui/212x64/model_setup.cpp
radio/src/opentx.h

Taranis menu always use 8 channels as default opposed to 9x and Horus, which use the maximum number as default channel count (which is 6 on dsm2). This commit does not change that logic.

Fix channel count on dsm2 module, purely cosmetic (closes issue #3673)

---

companion/src/firmwares/opentx/opentxinterface.cpp

urldecoding is already in place at receiving end

urlencode model string to allow models like x9d+

---

radio/src/opentx.cpp
radio/src/opentx.h

I like this better than #3724 the transition between speeds is more smooth. Try it and merge if you like it.

Re #3724: added smoothing filter for rotary encoder speed

---

radio/src/lua/api_general.cpp

This is my attempt to add haptic feedback support to lua scripts. I used haptic.play() even though OpenTX usually uses haptic.event() to generate haptic feedback. Tested working using the script below. I played with the parameters of that script but it seems that only "pause" has any effect, which is how long the haptic feedback is on. That value does not seem to correspond to milliseconds or even centiseconds... Thanks!
local inputs = {{"length", VALUE, 0, 100, 0}, {"pause", VALUE, 0, 100, 0}, {"flags", VALUE, 0, 1000, 16}, {"RepeatT", VALUE,0,100,10}}
local last_reset = getTime()
local function run(length,pause,flags,RepeatT)
local timer = getTime()
if (timer - last_reset) > RepeatT*10 then -- times 10 to convert to tenths of seconds
last_reset = timer
playHaptic(length,pause,flags)
end …

Haptic feedback in lua scripts

---

radio/src/switches.cpp

This adds the actual check on start and model change for Horus, to complement UI changes and saves already implemented.
Somewhat tested on X9E and HORUS dev, more test needed

HORUS : add actual pots and sliders checks to boot/model changes

---

companion/src/modeledit/inputs.cpp

Stops dropping inputs before Input1
Shift drag n drop (move) works
Has dependencies to Mixes drag n drop fix
Tested Ubuntu 14.04

Fixes Inputs Drag n Drop

---

radio/src/simu.cpp

This helps us people with non AZERTY keyboards that have Z left to the X. Doesn't help German layouts with 'Y' next to 'X' but that key is already used as trim key.

Add 'Z' as key to the rotary encoder emulation

---

radio/src/gui/480x272/radio_sdmanager.cpp

To be improved with a check that we are in the IMAGES folder (also on Taranis) for cleanliness

Allow selecting a model image from the SD manager (Fix #3814)

---

CMakeLists.txt

This is becoming a FAQ. File selection might not be perfect but is good enough to trigger the error.

Abort cmake if leftover files of 2.1 are found

---

radio/src/opentx.h

Tested on gcc 6.2 and 4.9.2
PLEASE test on CLANG and Visual Studio

Make abs macro AVR specific. This fixes gcc >= 6.2 compile issues. 

---

radio/src/lua/api_general.cpp

This allows the low and critical alarm levels to be accessed in lua. This also allows access to RSSI level without needing discovery.

Provide getRSSI() lua method

---

radio/src/tests/CMakeLists.txt

Set GTEST location variables as CACHE so they can be modified when gtest is in a different location from the cmake call (/usr/src, /usr/include is not writable on OS X)

Mark gtest variables cached

---

radio/src/opentx.cpp

This forces a stop at 0 in the following scenarios:
- you hit ext trims limit, then go back center with trims on coarse
- by changing trim steps, you end up in a place that does not stop at 0 (ex : fine, move to 12, set coarse, you move back to +4 and then -4 without center stop
Please someone check avr binary size , I have strange results on my compile pc
This fixes #3965

3djc/fix #3965

---

radio/src/targets/sky9x/sam3s2c_flash.ld
radio/src/targets/sky9x/sam3s4c_flash.ld
radio/src/targets/sky9x/sam3s8c_flash.ld

Copy .init and .fni section over from the STM32 linker scripts to make targets like AR9X buildable again. Tested by @sreichholf on a AR9X board

Fix Atmel ARM Linker script for gcc 5.4.1

---

radio/src/gui/480x272/model_select.cpp

Delay the checks until after the main menu is launched to avoid the model notes to be overwritten even before appearing.
This fixes #3777

3djc/fix #3777

---

radio/src/lua/api_general.cpp

This simplifies the LUA script in case SPORT is used as a transport for bigger requests (like MSP/SPORT). As of now, I have to build the chunk request, attempt sending, and if the buffer was not available, roll back to send buffer state to what it was previously. This change would allow to save CPU cycles, memory, and simplify the code within the LUA script.

lua: allow SPORT buffer availability to be queried

---

radio/src/opentx.cpp

that was not working when trim was changing from positive to negative.
Fixes the issue seen by Bsongis on Sky9X (but the issue was present on all platform)

Fix center trim stop

---

companion/src/modeledit/setup.cpp

directory instead of IMAGES directory for model images.

Fix Issue 4026 - Companion 2.2 Model Setup still using SD card BMP

---

companion/src/apppreferencesdialog.cpp
companion/src/customizesplashdialog.cpp
companion/src/helpers.cpp

Fix issue 4957 Taranis splash screens formatted incorrectly (for 9x) due to missed taranis to x9d name changes.

Fix issue 4957 Taranis splash screens formatted incorrectly.

---

radio/src/pulses/multi_arm.cpp

Fixed protocol selection for FQ777-124 and Assan protocols. These were being skipped because the code assumed FRSKYV had an ID of 23 when it actually has an ID of 25 in the multiprotocol tx module code.

fixed fq777-124 and assan protocol selection

---

companion/src/modeledit/customfunctions.cpp

Companion re-initialise a Special or Global Function's parameters when the selected function is changed #4103

Fixes #4103 Companion Special Functions parameters not cleared

---

radio/src/translations/tts_de.cpp

When precesion is set to 0,0 or 0,00 and the choosen value is 1,0 or 1,00 following happens:
eins meter
This is incorrect so i coded another part in the else part of "qr.rem > 0"  that checks if qr.quot is 1. If it is following happens now:
ein meter

Fixed a problem with precesion 0,0 0,00

---

companion/src/simulation/telemetrysimu.cpp

The log playback is extremely slow if the log frequency is .1s. So slow that it doesn't look like the playback is even working.
This fixes the issue.

fix log playback when log frequency is .1s

---

radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h

Centralize SD check condition. Also make some compiler checks more specific (eg. !minGW).

[simu] Fix Windows builds with SD-enabled targets; 

---

radio/src/gui/480x272/layout.cpp
radio/src/gui/480x272/layout.h
radio/src/gui/480x272/lcd.cpp
radio/src/gui/480x272/screens_setup.cpp
radio/src/gui/480x272/theme.cpp
radio/src/gui/480x272/theme.h
radio/src/gui/480x272/widget.cpp
radio/src/gui/480x272/widget.h

Fixes static initialization order problem with Layout, Theme, & Widget factories.  I discovered this when building simu with MinGW-w64.  The initialization depended purely on compiler "luck."
See [What’s the “static initialization order fiasco”?](https://isocpp.org/wiki/faq/ctors#static-init-order).
For example compare the registration order on Linux vs. Windows (from simu startup log):
Linux g++4.9:
```
$ ./simulator22
register theme Darkblue
register theme Default
register layout Layout1x1
register layout Layout2P1
register layout Layout2x1
register layout Layout2x2
register layout Layout2x4
register widget Gauge
register widget ModelBmp
register widget Outputs
register widget Text
register widget Timer
register widget Value
registering "opentx-horus" simulator
```
Windows MinGW-w64 4.9 …

Fix static initialization order problem with Horus GUI

---

radio/src/lua/api_general.cpp

prevent endless loop in sensor discovery if more than 7 is passed.

Protect subId

---

companion/src/constants.h
companion/src/simulation/CMakeLists.txt
companion/src/simulation/simulatordialog-9x.ui
companion/src/simulation/simulatordialog-flamenco.ui
companion/src/simulation/simulatordialog-horus.ui
companion/src/simulation/simulatordialog-taranis.ui
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatordialog.h
companion/src/simulation/simulatordialog9x.cpp
companion/src/simulation/simulatordialogflamenco.cpp
companion/src/simulation/simulatordialoghorus.cpp
companion/src/simulation/simulatordialogtaranis.cpp
companion/src/simulation/sliderwidget.h
companion/src/simulation/virtualjoystickwidget.cpp
companion/src/simulation/virtualjoystickwidget.h

And also height of Horus window. Possible fix for #3135 
One minor issue is that while this reduces the height of the Horus sim, it does increase the height of the Taranis and 9x sims by a few pixels.  
The width and height of the bottom part of the sim window are basically dictated by size the Output tabs, as shown in the screenshots.  It's a bit tight with 64 switches.  
One possible idea would be to move switches 33-64 to the 2nd outputs screen.  
Another would be to further reduce the size of the switch indicators, at a possible detriment to readability of the labels (though dropping the "L" should be OK?).
Or just leave it as is.  :)   (sorry, no OS X screens at this time...)

Reduce width of all simulator windows

---

companion/src/constants.h
companion/src/flashfirmwaredialog.h
companion/src/helpers.cpp
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatordialog.h
companion/src/simulator.cpp
companion/src/storage/appdata.cpp
companion/src/storage/appdata.h

- Radio profile used for standalone Simulator can now be separate from Companion;
- Allow selecting a radio profile and EEPROM image file (in addition to radio type) at startup via GUI and CLI;
- All startup settings are saved between uses.
- Save and restore Simulator window sizes and positions (based on selected radio profile).
- Set startup throttle stick lock in standalone sim based on default mode in selected radio profile (until we can read that from the model settings).
So the biggest change here is that you no longer have to go into Companion to switch radio profiles before starting sim with different radios.  Especially handy for developers & testers.  You still use Companion to create/edit profiles, as  before.
Though I ended up changing a lot of `simulator.cpp` in the process …

Standalone simulator startup options

---

companion/src/simulation/simulatordialog-horus.ui
companion/src/simulation/simulatordialog-taranis.ui
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatordialog.h
companion/src/simulation/simulatordialog9x.cpp
companion/src/simulation/simulatordialoghorus.cpp
companion/src/simulation/simulatordialogtaranis.cpp
radio/src/targets/common/avr/board_avr.h
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/sky9x/board.h

- Make key/mouse navigation more consistent between radios and ensure keyboard events are always properly detected (eg. after clicking on a control);
- Fix mouse wheel direction for rotary encoder emulation (fixes #4160);
- Fix page up/down buttons on Horus (closes #4160);
- Horus rotary encoder can now be controlled with +/- keys (also keeps X/C keys, otherwise supersedes #4087 and fixes key repeat issue);
- DEL key now another alternative for ESC/BKSP (brings all controls to number pad);
- "=" key now acts same as "+" key (+ requires SHIFT in main row on most US keyboards);
- Fix controls direction when using mouse wheel over RC switches;
- Add help text showing keyboard mappings for each radio type (activate on F1 key -- a button will be added in future changes).
- Enable mouse wheel …

Simulator key/mouse mapping improvements

---

radio/src/gui/128x64/model_logical_switches.cpp

Fix an X7 bug where logical switch value where displayed wrong for some types of fields.
While I was at it,  I changed to limits values from static values to getMaximumValue() to match the larger Taranis behavior.
I tested on X7, but it is very possible that this breaks other 128x64 (don't know enough to tell)
ps : my thanks to @kilrah for his ongoing support :)

3djc/x7: LS fix limits

---

radio/src/logs.cpp

Since https://github.com/opentx/opentx/commit/86ee89990577449775d7b700d8aed008ff2824a8, my x9e doesn't boot anymore.
What is happening is that deep inside storageReadAll(), there is a logsClose() call. And that function crash on some taranis (at least on mine !) if called before sdinit
This fixes the issue

X9e bootfix

---

companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/modeledit/setup.cpp
companion/src/modeledit/telemetry.cpp

I'm making a PR so the @kilrah can update his issue tracking post
Fix : RSSI alarms have the Orange/red dropdowns instead of low/critical
Also solves  : Telemetry / Horus: Protocol selection enabled when it shouldn't
Also solves : Telemetry screens should be hidden
Also solves : Model settings / Horus: Trainer settings missing

Companion : various fixes

---

.travis.yml
tools/commit-tests.sh

Check out the build times on the parallel builds vs. one single one... ~11-16min vs. 23+. Plus I added one more board (9XRPRO, not sure it's needed).  Plus you get to see results quicker, if one set of targets fails you still get tests on the others, and the logs are much shorter/easier to view.
Note that the [build summary](https://travis-ci.org/opentx/opentx/builds) page at Travis shows the total time for all the builds together.  You have to click through to the details to see the actual time.  The key point here is that the "sub-builds" run in parallel as slots become available.
Looks like Travis gives us up to 5 parallel builds across the whole repo (so that includes any other builds in progress).  So I have 6 now and the X7 build finishes quickly to open up a slot.  It could of …

[TravisCI] Set up for parallel Travis builds and use Qt5.7

---

radio/util/Dockerfile
tools/nightly22/build-nightly.sh

After lengthy discussion and many test, we feel we have to back down on this one, and offer a more mainstream and usable version.
We will continue to investigate ways to distribute more versions

Revert : Changes to allow Linux companion to be compiled with qt5.7 (#4262)

---

companion/src/mdichild.cpp
companion/src/mdichild.h

If we're ok to do that, should we not also automatically change every bin and hex file to .otx when opened?
Anything that might break or is storage type well decoupled from the extension now?

Force different file name after conversion

---

radio/src/translations/cz.h.txt
radio/src/translations/de.h.txt
radio/src/translations/en.h.txt
radio/src/translations/es.h.txt
radio/src/translations/fi.h.txt
radio/src/translations/fr.h.txt
radio/src/translations/it.h.txt
radio/src/translations/nl.h.txt
radio/src/translations/pl.h.txt
radio/src/translations/pt.h.txt
radio/src/translations/se.h.txt

It is a proposal to gain some space on busy 128x64 screens. Bellow are some example on how it looks.

Shorten GVx to Gx on 128x64 radios, where screen estate is a real issue

---

companion/src/CMakeLists.txt
companion/src/helpers.cpp
companion/src/simulation/CMakeLists.txt
companion/src/simulation/joystickdialog.cpp
companion/src/simulation/joystickdialog.h
companion/src/simulation/joystickdialog.ui
companion/src/simulation/simulateduiwidget.h
companion/src/simulation/simulator.h
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatordialog.h
companion/src/simulation/simulatordialog.ui
companion/src/simulation/simulatorstartupdialog.cpp
companion/src/simulation/simulatorstartupdialog.h
companion/src/simulation/simulatorstartupdialog.ui
companion/src/simulation/widgets/radiofaderwidget.h
companion/src/simulation/widgets/radioknobwidget.h
companion/src/simulation/widgets/radioswitchwidget.h
companion/src/simulation/widgets/radiowidget.cpp
companion/src/simulation/widgets/radiowidget.h
companion/src/simulator.cpp
companion/src/storage/appdata.cpp
companion/src/storage/appdata.h

Continued from #4260 
Multiple changes and new features:
*  All Horus data source options are now fully supported with data properly saved after use (SD path, .otx file, or custom data path);
*  Loading .otx files now works for all radio types (but not yet saving data back to .otx, except on Horus);
*  Switch and knob/slider states are now saved to the Companion radio profile (and switches are now "up" by default);
*  Joystick configuration/calibration is now available directly from inside Simulator;
*  **!** Due to refactoring, all previously saved per-profile simulator settings are now invalid (sorry, but the new ones are better! :)
*  With WIN_USE_CONSOLE defined, Simulator and Companion when started from Windows command line will now use that console for all messages (instead of …

[Simulator] Further Simulator improvements.

---

radio/src/lua/api_general.cpp

Followup on #4232: DIY ID range changed to 0x5000 - 0x52FF

Update the luadoc for sportTelemetryPop()

---

companion/src/eepromimportexport.h
companion/src/firmwares/opentx/opentxeeprom.h
companion/src/firmwares/opentx/opentxinterface.cpp

Loading a bad .otx resulted in segfault because input bits array was smaller then for example radio data array. 
Qt does assert when accessing QByteArray[n] with n >= size.
```
ASSERT: "i >= 0 && i < size()"
```

Prevent Companion crash if input data is smaller than required

---

radio/src/gui/480x272/model_curves.cpp

After looking at the Taranis GUI code, I decided to emulate what that
does, which is just skip over the X coord line in the menu if when
curve type is custom and points is <= 2.
TESTING DONE:
Tested Horus in the simulator. Trying a variety of combinations of 2 and 3 point custom and standad curves while using the rotory dial to scroll thru the menu positions.

Fix for #4222: On Horus GUI, can't edit X values for < 3-point curves.

---

companion/src/modeledit/setup.cpp

Fix display when module is OFF
This fixes "Horus: Internal/external antenna choice showing up even if internal module is OFF (should be in modulePanel too)" in #4224

Move antenna switch to module switches

---

companion/src/mdichild.cpp
companion/src/mdichild.h
companion/src/modelslist.cpp

- Adds "rename" to the context menu for categories, it uses the
same code path as the default dblClick handler for the base class.
- Added a separator so the context menu looks more like the one
for models
- Some whitespace changes in mdichild.h, my editor truncates
whitespace on blank lines. Let me know if you don't like this.

Re #4224 Add "rename" item to Category context menu in companion.

---

radio/src/targets/simu/simpgmspace.cpp

The old implementation broke on OS < 10.12. Let the C++ stdlib handle the mess.

Use C++11 clock implementation instead implementation platform specific code ourselves

---

radio/src/datastructs.h

Since X7 is released now, we should not modify its data struct sizes anymore
X7 is too different from Taranis/sky9x to merge it into one of the other blocks

Check X7 epprom sizes

---

companion/src/mdichild.cpp
companion/src/mdichild.h

Issue #4224. Allow pasting models into and across categories. This one is actually on the list for #4224. 
To do this, we need both the current category and model index
passed into doPaste(), which then decides if the user is pasting
into a category based on whether or not modelIdx == -1.
Doing a category paste just means we stub out a ModelData object,
insert it into the models vector then use the existing code to
paste over it.
Also, the code now allows users to copy/paste models across
categories.
Testing Done:
- With Horus radio profile
- I tried various combinations of pasting single models and multiple models onto existing models, on to blank new categories and existing categories. Saved, reopened, it all looked fine.
- With Taranis radio profile
- I tried various combinations of …

Issue #4224: Paste into and across categories in Companion

---

companion/src/mdichild.cpp
companion/src/mdichild.h

Just what it says in the title, implement the "duplicate model" action in
Companion's context menu. This isn't actually listed in #4224, but it
feels like something that would be and I couldn't find a separate issue
for this.
Also, fixed "modelAdd" so that it only sets the default model if it just
added the first one. Previously, the newly added model would become the
default, which seemed like the wrong thing.

Issue #4224: Implement "duplicate model" in Companion

---

companion/src/mdichild.cpp
companion/src/mdichild.h
companion/src/modelslist.h

Fixes issue #4375.
With category-capable radio profiles, finding the next row to paste into mean following the UI rows rather than just getting the next model in radioData. Also, we have to account for possibly pasting "off-the-end" of the category. In that case, the extra models in the paste data will end added to the same category. 
For non-category capable models, the same code works (I tested on Taranis profile!)  because the UI layout appears sort of like one big category.

Issue #4375, fix pasting multiple items in Companion.

---

companion/src/storage/categorized.cpp

The previous code  didn't account for this situations where the models vector
contained models from category 1, followed by models from category 2,
followed by models from category 1. In this situaion, models.txt would have
two categories named "category 1". 
The overall problem is that we need to output models to models.txt sorted first by category index than by model index.  I'm not really happy with the approach here, but I this is what came to mind:
- Create a map: of category indices to a vector of model indices 
- While running thru the models vector writing .bin files, store indices to models and categories in sortedModels. For category-less models, store them with map key '-1' 
- When done, iterate over known category indices in the map, outputting the category line followed by …

Issue #4368. Don't duplicate categories in OTX's models.txt

---

radio/src/telemetry/frsky.h
radio/src/telemetry/frsky_sport.cpp

Fixes telemetry stream confusion. 
0x5100 to 0x51ff is DIY stream data, 
0x5200 to 0x52ff is diy sensor data and is treated the same as any other telemetry packet.

Fixes telemetry stream confusion

---

radio/src/cli.cpp
radio/src/gui/480x272/bitmapbuffer.h
radio/src/gui/480x272/screens_setup.cpp
radio/src/gui/480x272/view_statistics.cpp
radio/src/gui/480x272/widget.h
radio/src/lua/api_general.cpp
radio/src/lua/api_lcd.cpp
radio/src/lua/api_model.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h
radio/src/lua/widgets.cpp

Lua: Use incremental GC and also call it for Widgets
Fixes #3885: Error in Lua Widget options handled better (does not disable entire Lua state)
Disable Lua Widget if any of its functions has error.
This is a rough concept:
* if a widget has Lua erorr, remember error and disable offending widget (it is still availabe in factory, should it be removed from there also?)
* show widget error to user in widget settings screen   (very rough, should be improved visually)
* I thought GC was running in Lua automagically, looks like it is not, lua_gc() call is needed, this commit also fixes this. The Scripts are also not GC so aggressively now (was always full GC). Needs testing and tuning (amount of work for incremental GC can be tuned).
* Added a variable that keeps the total value of memory used …

Several Lua improvements for stability

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/212x64/lcd.cpp
radio/src/telemetry/telemetry.cpp

With this fix, it is working fine, but maybe could be improved later by moving to right aligned
X7:
This closes #4382

Fix GPS display in telem screen for X9. 

---

radio/src/gui/480x272/screens_setup.cpp
radio/src/gui/480x272/widget.h

When compiling on OSX with px4/px4/gcc-arm-none-eabi: stable 20160928, I was getting const errors with a recent gcc. 
So I removed the const modifer to Widget::update in the 480x272 GUI. This caused menu_settings.cpp menuSettings() to complain, because it was being passed a param called
'object' of type pointer to a const T, and then called object->update(),
which is not a const function.
However, the one call site I found to menuSettings() (menu_settings.cpp:224)
is passing currentWidget, which is of type Widget*. 
'currentWidget' is a static though, and I don't have the full picture on this code yet, so maybe there's a problem with multithreaded use that the const-ness was trying to solve?

Removed const modifer to Widget::update in the 480x272 GUI.

---

companion/src/simulation/debugoutput.cpp
companion/src/simulation/radiooutputswidget.cpp
companion/src/simulation/radiooutputswidget.h
companion/src/simulation/simulatordialog.ui
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatormainwindow.h
companion/src/simulation/simulatormainwindow.ui

Main  window:
* Fix floating dock widgets appearing behind other applications on Linux (https://github.com/opentx/opentx/issues/4403#issuecomment-277510273);
* Fix previously-unused floating dock widgets appearing in top-left corner upon subsequent launches of application (https://github.com/opentx/opentx/pull/4385#issuecomment-277315158);
* Fix various anomalies due to not using a "central widget" in QMainWindow (extra separators appearing, vertical resize not working in some cases (https://github.com/opentx/opentx/pull/4385#issuecomment-277315158)), radio widget is now central by default;
* Add (keep) option to float the radio widget separate from main window, though this may cause the minor visual anomalies mentioned above;
* Add options to disable radio widget size constraints while …

[Simulator] UI tweaks for last major update.

---

radio/src/gui/128x64/model_setup.cpp

With this version, the switch been edited is both blinking and inversed, which seemed most natural to me when editing. Another version (https://github.com/opentx/opentx/tree/3djc/X7-sw-warning) has those blinking for editing, and  blinking+invers for editing activated
This closes #4401

X7 switch warning setup

---

companion/src/helpers.cpp
companion/src/simulation/simulatordialog.cpp
companion/src/simulation/simulatordialog.h
companion/src/simulation/simulatorinterface.h
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatormainwindow.h
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/opentxsimulator.h

This could use some testing to make sure all the various startup permutations are covered and data is properly updated.
(Did I miss any?)
Radio & model settings should be saved back to the file/data path in all cases except when launched from within Companion.
Also, I could not find an existing way to get radio data back from SimulatorInterface, so I created the new `readEepromData()` function.  But if I missed an existing method, or there's a better way to go about this, I'm all ears.
All `libsimulator` flavors need to be rebuilt after this change, the old versions WILL crash when launched with this Simulator/Companion.
Thanks,
-Max

[Simulator] Add ability to update .otx files.

---

radio/src/gui/128x64/model_setup.cpp

Using arrow a bit like x9, while keeping X7 menu behaviour.
ENT on a switch enables or disable that switch check (when anble, and arrow or - is played, when disabled, a blank space)
Long ENT while anywhere in that line stores the positions

X7 switch warning, take 2

---

companion/src/translations/companion_fr.ts

Rotary Encoder is now translated in "Sélecteur Rotatif" with the abbreviation "Sel.Rot."

Updated again French Translation.

---

radio/src/gui/480x272/model_setup.cpp
radio/src/sdcard.h

Limit filename to 6 as sdcardfilelist controls size without extension (and size with ext was sent).
This closes #4415

Horus : limit model bitmaps filemane to 6 chars

---

radio/src/gui/128x64/radio_diagkeys.cpp

Did this ever work?  Pressing "keys" made the "switch" indicators light up also.  Thought I broke something with my keymapping changes (#4175), but no. Tested on an actual stock Tgy. 9X (which I "forgot" I had!).  
The #ifdef is not strictly necessary, but clarifies the new function isn't used for X7 (sorta... X7 is "PCBTARANIS" also I assume).

Fix switch diagnostics display on 9X family.

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/128x64/view_channels.cpp
radio/src/gui/128x64/view_main.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/gui/212x64/view_channels.cpp
radio/src/gui/480x272/model_mixes.cpp
radio/src/gui/480x272/model_setup.cpp
radio/src/gui/480x272/view_channels.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp

* Adjust custom failsafe (and some channel display) ranges for proper extended limits (fixes #4447).  
* Fix some display issues in x64 GUIs when adjusting failsafe settings, and cleans up code in those functions.
* Fix 480x272 channel output progress bars to show full extended limits.
* Fix alignment issues on 212x & 480x gui mixes screens with long custom channel names.
* Streamline some channel outputs display code.

[firmware][gui] Extended limits fixes, issue #4447

---

companion/src/mainwindow.cpp
companion/src/mdichild.cpp
companion/src/mdichild.h

Fixes Alt-S not always activated when needed
Fixes edit menu for Horus (activated for models, not category)
This fixes #4349

Menu updates handling cat/models for Horus

---

companion/src/simulation/CMakeLists.txt
companion/src/simulation/debugoutput.cpp
companion/src/simulation/debugoutput.h
companion/src/simulation/debugoutput.ui
companion/src/simulation/filteredtextbuffer.cpp
companion/src/simulation/filteredtextbuffer.h
companion/src/simulation/simulatormainwindow.cpp

FIFO device runs in own thread(s) w/out blocking GUI thread.
Merging in #4484 makes the whole thing more efficient due to half the number of callbacks required to handle the output (currently each CRLF is sent in a separate event from main text body).
There will probably be a minor conflict with #4475 so depending on which is merged first (or at all), I'll fix the other.

[Simulator] Add asynchronous FIFO buffer for handling debug output/display more efficiently.

---

radio/src/debug.h

I also propose we prefix TRACE with `-T- ` (or `-D- `) for easier filtering.  Important messages meant for end-users should be sent with `TRACE_[INFO|WARNING|ERROR]` (not sure if that's always the case now).
I also like Damjan's suggestion of prefixing the individual TRACE_module macros, like: https://github.com/opentx/opentx/pull/4458/files#diff-fbb61f947eba942385bf18e8b1e4a20dR72
I'm also wondering if we could reduce the flood of TRACE_SIMPGMSPACE messages at Horus startup somehow.  I realize it can be useful which is why I don't like disabling that trace entirely in the build, but ~500 lines at startup seems a bit much and becomes less useful in my opinion.
Thoughts?

[radio] Improve TRACEs

---

radio/sdcard/horus/S6R/S6R.lua
radio/src/lua/api_lcd.cpp

Allows to specify a blanking color when using it on color screens

Make lcd.clear() color aware on color screens

---

radio/src/cli.cpp
radio/src/gui/480x272/radio_sdmanager.cpp
radio/src/gui/480x272/widgets.cpp
radio/src/gui/common/stdlcd/radio_sdmanager.cpp
radio/src/sdcard.cpp
radio/src/storage/eeprom_rlc.cpp
radio/src/storage/rlc.cpp

A couple of problems were found using `-DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=leak"` and then running `simu`.
More reading https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer and https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
Example error before this fix:
```
==13966==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000735e52 at pc 0x00000044bf9c bp 0x7f419aa7ec40 sp 0x7f419aa7ec30
READ of size 1 at 0x000000735e52 thread T6
#0 0x44bf9b in RlcFile::nextRlcWriteStep() /radio/src/storage/eeprom_rlc.cpp:681
#1 0x44a9c3 in RlcFile::nextWriteStep() /radio/src/storage/eeprom_rlc.cpp:430
#2 0x4356ee in eepromWriteProcess() (/build-x7/simu+0x4356ee)
#3 0x434e06 in checkEeprom() /radio/src/main_arm.cpp:72
#4 0x435566 in perMain() …
```

Some memory leaks and out of bounds array access fixed

---

companion/src/modeledit/expodialog.cpp
companion/src/modeledit/expodialog.h
companion/src/modeledit/mixerdialog.cpp
companion/src/modeledit/mixerdialog.h

Companion part of #3305. Any votes for adding to radios or close the issue with this PR?
Apologies for the messy diff caused by the indent changes.
Suggestions for shortening the fm checkbox pointer array initialisation code welcome. New at c++ and tried a number of syntax variants based on web searches but kept hitting compiler errors.
Tested on Ubuntu 16.04

Fixes #3305 Companion model edit add clear, set and invert all flight modes context menu

---

companion/src/modeledit/setup.cpp
companion/src/modeledit/setup.h
companion/src/modeledit/setup_module.ui

* Properly set limits based on model's Extended Limits setting;
* Fix rounding issues between percentile display and underlying value in μs;
* Add ability to display values in μs or percent.
* Channels numbering & count is responsive to module's defined start/end channels.
Fixes #4443
Please give this a good test first... I'm a bit rushed on final testing, and may be not be available for a few days for quick fixes.  I did give it a good workout, but you never know.  Thanks!

[Companion] Fix/improve setting radio module custom failsafe values.

---

radio/src/CMakeLists.txt

Commit ab6f910 added filename markers to allsrc.cpp, those subsequently got broken at some point.
This PR fixed the regression.
Filename markers are helpful when trying to figure out which file contains compilation errors.

Fix a regression that omitted filenames from allsrc.cpp

---

radio/src/gui/128x64/model_select.cpp
radio/src/gui/128x64/popups.h
radio/src/storage/eeprom_rlc.cpp

To allow restore, I've had to increase MENU_LINE_LENGTH, could not find adverse effect, but want to warn about it
This fixes #4511

Allow datestamp for ARM 128x64 model backups

---

radio/src/.gitignore

without this, i get:
```
CMake Error at CMakeLists.txt:88 (message):
Source directory contains files leftover from a OpenTX 2.1 build.  Please
run `git clean -f` in source directory (Careful: Will remove any extra
files) or do a new clean git checkout
```
but `git clean -f` does not remove `stamp.h`

remove src/radio/stamp.h from the gitignore (make cmake idempotent)

---

radio/src/thirdparty/GCS_MAVLink/sync

Updated GCS_MAVLink sync script that was broken on current mavlink master due to directory structure changes and submodules added to mavlink repo https://github.com/mavlink/mavlink.
Current version of protocol definitions in GCS_MAVLink dir is 3 years old and is missing RC_CHANNELS message  that contains RSSI in PX4 mavlink implementation.
This missing definition prevents adding support for PX4 RSSI to mavlink telemetry code.
Prerequisites: `sudo pip install future` or `sudo apt install python-future`
This script DOES NOT run automatically during build, so no immediate impact on build process.
Updated headers (after running the script manually) need a one-line source change to mavlink.cpp, provided here: https://github.com/alteman/opentx/commit/57167df663889bd8fbf9abf0a96a4d85c65f9595. …

Update GCS_MAVLink sync script to work with updated mavlink repo

---

companion/src/boards.cpp
companion/src/boards.h
companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/helpers.cpp
companion/src/modeledit/expodialog.cpp
companion/src/simulation/simulatorwidget.cpp

Fixes bug in #4336.  JSx/JSy are available in the same lists which now show pots/sliders.

[Companion][Horus] Add joystick axes (JSx & JSy) and trims T5 & T6 as usable sources.

---

companion/src/mdichild.cpp
companion/src/mdichild.h

The new option is only shown if > 1 categories exist.
Ref. #4224 : Horus models cannot be moved from one category to another.

[Companion] Add context-menu actions for moving a model between categories.

---

radio/src/simu.cpp

As with Simulator, the pot must be "calibrated."  This is because the current [radio code](https://github.com/opentx/opentx/blob/mpaperno/simu_6pos/radio/src/switches.cpp#L253) won't even try to read the switch/pot positions w/out at least some valid calibration data ( 👍 ).
This is just hard-coding the 6-pos switch with yet another `#ifdef`... open to better ideas or if anyone thinks the 6-pos should be added to other radio(s) also.

[simu][horus] Replace 2nd knob/pot with functional 6-pos switch

---

radio/src/telemetry/mavlink.cpp

Add support for displaying Mavlink RSSI from PX4 firmware.
Note that scaling from 255 to 100 in REC_MAVLINK_MSG_ID_RC_CHANNELS_RAW is not up to Mavlink spec https://pixhawk.ethz.ch/mavlink/#RC_CHANNELS
> rssi	uint8_t	Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.

Add support for PX4 RSSI

---

radio/src/lua/api_lcd.cpp

This fixes : #4567
Fix and simplify lcd.drawlines. Executing:
```
lcd.clear()
-- outward star
xc = LCD_W / 4
yc = LCD_H / 2
lcd.drawPoint(xc, yc)
lcd.drawLine(xc, yc, xc+10, yc, SOLID, 0)
lcd.drawLine(xc, yc, xc-10, yc, SOLID, 0)
lcd.drawLine(xc, yc, xc, yc+10, SOLID, 0)
lcd.drawLine(xc, yc, xc, yc-10, SOLID, 0)
lcd.drawLine(xc, yc, xc-10, yc - 10, SOLID, 0)
lcd.drawLine(xc, yc, xc+10, yc+10, SOLID, 0)
lcd.drawLine(xc, yc, xc+10, yc-10, SOLID, 0)
lcd.drawLine(xc, yc, xc-10, yc+10, SOLID, 0)
-- inward star
xc = xc + (LCD_W / 2)
lcd.drawPoint(xc, yc)
lcd.drawLine(xc-10, yc, xc, yc, SOLID, 0)
lcd.drawLine(xc+10, yc, xc, yc, SOLID, 0)
lcd.drawLine(xc, yc-10, xc, yc, SOLID, 0)
lcd.drawLine(xc, yc+10, xc, yc, SOLID, 0)
lcd.drawLine(xc-10, yc-10, xc, yc, SOLID, 0)
lcd.drawLine(xc+10, yc+10, xc, …
```

LUA drawline fix

---

companion/src/storage/firmwareinterface.cpp

Fix for companion firmware compatibility check failing under new firmware names (opentx-x12s, was previously opentx-horus)

Fix for issue #4590

---

radio/src/dataconstants.h

We have several failed compilation on the server with this error:
audio_avr.cpp: In function 'void audioTimerCountdown(uint8_t, int)':
audio_avr.cpp:298:51: error: 'COUNTDOWN_HAPTIC' was not declared in this scope
Since there is code in avr that deal with it, I'm assuming that it should be ok to declare for avr too

Allow HAPTIC to be defined for avr too

---

radio/src/targets/simu/simpgmspace.cpp

`GetTickCount[64]()` has poor resolution.  https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408(v=vs.85).aspx

[Simulator] Improve CoGetOSTime() for MSVC.

---

companion/src/CMakeLists.txt
companion/src/companion.cpp
companion/src/customdebug.cpp
companion/src/customdebug.h
companion/src/eepromimportexport.h
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/CMakeLists.txt
companion/src/modeledit/channels.cpp
companion/src/simulation/debugoutput.cpp
companion/src/simulation/debugoutput.h
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatorwidget.cpp
companion/src/simulation/simulatorwidget.h
companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/widgets/lcdwidget.h
companion/src/simulator.cpp
companion/src/storage/firmwareinterface.cpp
companion/src/storage/storage.cpp
companion/src/storage/storage.h
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simueeprom.cpp
radio/src/targets/simu/simufatfs.cpp

A bunch "small" fixes all bunched together... pre-squashed, if you will (I cold break them up but if they'll be squashed anyway... this was easier).  These should probably be included in next 2.2 RC.
* [simpgmspace] Init trims; Make sure `REa` is really defined (to match board files).
* [simpgmspace][opentxsimulator] Verify current running state before start/stop; Move rotary enc. init.
* [simpgmspace][LcdWidget] Improve performance by moving LCD content change check to lcdRefresh() & limiting LcdWidget refresh time to 60 fps max; Ensure thread safety with shared LCD buffer.
* [simueeprom] Ensure thread could be started, set default running state to false.
* [simufatfs] Fix paths report trace.
* [eepromimportexport] Fix memory leaks resulting from import debugging scheme being used.
* …

[simulation] Fix some potential crashes & 26 memory leaks, improve LCD redraws.

---

radio/src/gui/gui_common_arm.cpp

The removal of the static might fix #4641 if there is some linking problem. Anyway even if it does not fix the bug, the increased consistency is nice.

Define multi subtype strings in the same way as all other strings

---

companion/src/companion.cpp
companion/src/customdebug.cpp
companion/src/customdebug.h
companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/helpers.cpp
companion/src/simulation/simulatorinterface.cpp
companion/src/simulation/simulatorinterface.h
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatormainwindow.h
companion/src/simulation/simulatorstartupdialog.cpp
companion/src/simulation/simulatorstartupdialog.h
companion/src/simulator.cpp

As discussed with Damjan, this will give a "fresh start" every time simulator is launched from Companion, possibly preventing old data from sticking around.  For example, right now if you exit simulator while an audio track is playing, and then re-launch it, you will hear the rest of the audio track which got cut off the first time (because the buffer is never cleared). This is a non-destructive example, but helps illustrate the point I think.
Note that in this version pressing the "restart radio" button in Simulator will **not** reload the library (more like a "soft reset").  This is doable but will take a little more coordinating with the sub-windows (since simulator object gets deleted).
Tested in all 3 OSs (with Qt 5.2, 5.3, & 5.7 on Linux), and fully profiled and leak-proofed in Win …

{Companion] Unload simulator libraries after each use -- reset all statically initialized firmware variables.

---

radio/src/lua/api_lcd.cpp

Produces a segfault with the telenowa script (missing bitmap)

Fixes #4589

---

companion/src/CMakeLists.txt

* Refactor condition to avoid repeating the test in `else` and `endif`;
* Suffix programs name with `${C9X_NAME_SUFFIX}` under FreeBSD, as for
Linux build, else cmake build is failing because a `companion`
directory already exist in the build directory.
---
I do not remember having this issue on master branch, but I see code
is similar, so I'll check why I didn't needed this later.

Improve companion CMake programs name condition

---

radio/src/gui/common/stdlcd/model_mixes.cpp

If three is a mixer name, it is displayed, but on active row, the name is moved to title bar, and data is displayed instead
This fixes #4690 
For reference : #4281

Fix non overlapping text

---

companion/src/modeledit/customfunctions.cpp
companion/src/modeledit/logicalswitches.cpp
companion/src/modeledit/logicalswitches.h

By only displaying Logical Switches and Special Functions which are actually used.  I get ~2-3x faster startup times, which is significant.  
Personally I think it looks a bit cleaner as well.  But please correct me if there's actually a reason to show the lines when no function/switch is assigned.  
I have some other changes which help but this was the biggest impact with the least code.   Most of the diff is due to indent changes.  It simply skips a lot of the code now if a function/switch isn't set for a line.

[Companion] Speed up loading of model editor

---

companion/src/burnconfigdialog.cpp

Add paths for avrdude and dfu-util programs under FreeBSD. SAM-BA does
not exist yet in the FreeBSD port collection.

Add firmware update tools location for FreeBSD

---

radio/src/targets/simu/simpgmspace.cpp

Fix 2MHz and 16KHz timers on MSVC builds.  Fixes LCD/key/switch response delay on all AVR simulators.  Apparently has been broken for quite some time...
Tested on MSVC2015, MinGW 5.3, Linux GCC 4.8 & 4.9, OS X clang 8.
Also introduce experimental use of Qt to possibly simplify x-platform code in future (disabled by default).

[Simulator] Fix timing issues in all AVR simulators on Windows (MSVC)

---

companion/src/modeledit/modeledit.cpp
companion/src/modeledit/modeledit.h

Now acts the same as simulating a model from the models list widget using "Simulate Model" menu item (that is, including the other radio data as well, whereas before a default radio data object was created and the model inserted into that).  
Besides simplifying the code, making it more consistent with the other way to simulate a model, and removing the extra category name (re: #4712), I'm not sure it makes sense to simulate a model w/out the rest of the radio data -- what if the model relies on general settings like global functions?

[Companion] Change simulator startup from ModelEdit panel.

---

companion/src/apppreferencesdialog.cpp
companion/src/apppreferencesdialog.ui

Re: #4686
(Didn't test that the actual flashing works now, but it does wipe the splash image name correctly from profile settings when Horus radio type is selected).

[Companion] Improve handling of non-supported splash image (Horus) in radio profile settings page.

---

radio/src/storage/modelslist.h

This deals with "Models with an empty name converted to Horus should have their default name set"
of #4224

Horus : use filename when no name is defined

---

companion/src/mdichild.cpp

This deals with part "Allow eepe files only for opening, not for saving"
of #4224

Only allow saving to OTX format

---

companion/src/mainwindow.cpp
companion/src/mainwindow.h

Thix fix #4686 
Thix changes current behaviour of copying current profile when creating a new one. Given the differences in radio capabilities and working principles, this protects from carrying not relevant, sometime incompatible data

Instead of copying current profile, start from a blank one

---

README.md

We show next as default branch. Include the useful links in 2.2 as well.

Copy useful links from 2.1 to 2.2

---

companion/src/apppreferencesdialog.cpp
companion/src/apppreferencesdialog.h
companion/src/apppreferencesdialog.ui
companion/src/companion.cpp
companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/fwpreferencesdialog.cpp
companion/src/mainwindow.cpp
companion/src/mainwindow.h
companion/src/simulator.cpp

* Fix possible confusion/data corruption when deleting radio profile (closes #4734, ref: #4686);
* Add Delete Profile action to Radio Profiles menu (closes #4736) (but remove from app prefs. panel);
* Add confirmation prompt before deleting profile;
* Open profile settings dialog when creating/copying a profile (closes #4735);
* Make sure current (global) firmware flavor is properly updated when changing fw type/options in profile;
* Append "-Copy" to name of copied profile;
* Factor out Firmware global vars/functions in favor of static members.

[Companion] Improve radio profile/current firmware handling.

---

radio/src/lua/api_general.cpp

Allow to query a telemetry sensor unit using lua getFieldInfo()
this closes #4747 #3334

Add unit to lua getFieldInfo

---

radio/src/gui/480x272/bitmapbuffer.cpp
radio/src/gui/480x272/lcd.cpp

Horus : adjust INVERS background for all text sizes

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/gui/480x272/model_setup.cpp

This is when someone pushing RTN/EXITG before making an actual mode choice, et would get  kinda stuck with binding selected but not working

Binding popup : handles premature exit (no pun intended)

---

radio/src/storage/eeprom_rlc.cpp

Clang complains about startP pointer pointing to a member of a packed structure, resulting on in a unaligned pointered address. The compiler will optimise the pointer out anyway

Remove unused pointer startP

---

radio/src/telemetry/flysky_ibus.cpp

In my first implementation I guess some scalings wrong (and forgot PREC1 when trying to subtract 40)

Fix IBUS telemetry scaling

---

radio/src/targets/taranis/keys_driver.cpp

This fixes #4650 
Successfully tested with:
with the pull down resistor present or not.
WARNING : this change will require X9E owners using extra 2pos or toggle switches to review their settings. Previous version (2.1 or 2.2) where reading incorrectly those switches toggling between middle (which should not exist for a 2pos/toggle) and either up or down (depending on how they are wired). This was generally not seen as an issue because Companion was not able to display/manage those, and the functionality seemed ok

X9E : better manage additional switches declared as toggle or 2pos

---

radio/src/gui/480x272/radio_setup.cpp
radio/src/rtc.h

Year set is called with 112, 200 limits, overflowing the int8_t type
This fixes #4627

Move tm_year to unsigned

---

radio/src/gui/128x64/model_special_functions.cpp
radio/src/gui/212x64/model_special_functions.cpp
radio/src/gui/480x272/model_special_functions.cpp

Please review that I choosed the right limit for global functions
This fixes #4810

Do not allow past SWSRC_TELEMETRY_STREAMING for global functions

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/212x64/lcd.cpp

drawSource was not displaying name when defined for the last POT source. on x7 and x9
X12 does not seem to be exhibiting the issue
This fixes #4840

fix drawSource

---

radio/src/io/frsky_sport.cpp

Use hardware revision to help troubleshoot user error.
This fixes #4847

X7 : Differentiate message for external flashing

---

companion/src/translations/companion_fr.ts

- `Éditier` should be `Éditer`
- `SWR` is now `RAS`

Fixed typo.

---

radio/src/gui/128x64/radio_diaganas.cpp
radio/src/gui/212x64/radio_diaganas.cpp
radio/src/gui/480x272/view_statistics.cpp

This is an addition to https://github.com/opentx/opentx/commit/37b0dab9dadadfa8d39fb0af491526680c832175
Only display RAS when we know there is a valid source for it

Only display RAS for XJT modules

---

companion/src/translations/companion_fr.ts

Logical switch `L%` or `LSw%` are now translated in `IL%` (Interrupteur Logique).

Updated L/LS/LSw  French translations

---

companion/src/constants.h
companion/src/flasheepromdialog.cpp
companion/src/mainwindow.cpp
companion/src/mdichild.cpp
companion/src/simulation/simulateduiwidget9X.cpp
companion/src/simulation/simulateduiwidgetX12.cpp
companion/src/simulation/simulateduiwidgetX7.cpp
companion/src/simulation/simulateduiwidgetX9.cpp
companion/src/simulation/simulateduiwidgetX9E.cpp
companion/src/simulation/simulator_strings.h
companion/src/simulation/simulatorstartupdialog.cpp

This will not require re-translating anything, just updates the system to actually use any translations already available (macros using `QT_TRANSLATE_NOOP` macro apparently do not work).  Only affects simulator keymap help strings, and some prompts in file selector dialogs.

[Companion] Fix a few translations.

---

radio/src/translations/tts_it.cpp
radio/util/tts_it.py

- generate proper translation for hours minutes and seconds (this WILL require a sdcard version increment)
- Switch the time mechanic to english one, with italian words. It is likely not perfect, but probably usable, while current italian audio timers are not working at all
This fixes #4186 until further details are given

Italian audio timers

---

companion/src/generaledit/hardware.cpp
companion/src/generaledit/hardware.h
companion/src/generaledit/hardware.ui

- Hide external serial port option for Horus; 
- Fix battery voltage and current calibration changes not registering (wrong signal handler name); 
- Prevent modified() event if edited value wasn't actually changed (this is a problem in all panels with onEditingFinished() signals if focus is placed & removed on an editable field by eg. click or tab); 
- Fix some cosmetic layout issues when no hardware names are editable (vertical stretch, extra separators).

[Companion] Some radio settings Hardware tab fixes.

---

companion/src/modeledit/setup.cpp
companion/src/modeledit/setup.h
companion/src/modelprinter.cpp

Eg. when populating protocols box or when removing focus from some fields w/out the value actually changing.  Especially affects OS X which puts the focus in the model name field by default and (at least in some cases) emits the modified signal right away even when nothing changed.  Similar to #4895 in that respect.

[Companion] Model Setup: Prevent bogus modification signals.

---

companion/src/mainwindow.cpp
companion/src/mainwindow.h
companion/src/process_sync.cpp
companion/src/process_sync.h
companion/src/progressdialog.cpp
companion/src/progressdialog.h
companion/src/progressdialog.ui
companion/src/progresswidget.cpp
companion/src/progresswidget.h
companion/src/progresswidget.ui

* Complete re-write of SyncProcess, now more robust, UI-independent, runs in own thread, large speed boost;
* Use file hash comparisons instead of old method with QStrings and text stream (probable fixes for #4837 and #4848);
* New pre-sync options dialog with selectable folders and other settings (settings are remembered until app exit);
* Option to choose sync direction(s) (up/down/bi) and the order in which bi-directional sync runs;
* Option to choose file comparison mode (timestamp/hash/both) or force overwrite (for one-way sync);
* Option to set a maximum file size to copy;
* Option to do a test run w/out actually copying any files;
* Better reporting of progress, total counts (copied/updated/skipped), and errors, with color coding;
* Much more reliable to cancel long-running/hung …

[Companion] SD Sync reworked.

---

companion/src/eeprominterface.cpp
companion/src/modeledit/expodialog.cpp
companion/src/modeledit/inputs.cpp
companion/src/modeledit/mixerdialog.cpp
companion/src/modelprinter.cpp

Re: #4879 
With colons after input number:
Without colons (current version of this code):
(Those are from someone's actual radio file.)
I'd rather just pick a version and stick to it, vs. making exceptions in the code for the different view types.  If we're to have exceptions then they should at least be systematic, eg. a "verbose" view vs. "short" view, or whatever.  IMHO.

[Companion] Input names formatting 
