opentx/opentx

radio/src/lcd.h

Still doesn't take the different characters sizes into account...

Little lcd_putsCenter correction

---

radio/src/targets/stock/board_stock.cpp

Fixes #1970 for the next branch.

Port ATmega2561 PWM_BACKLIGHT fix from master branch

---

companion/src/translations/companion_it.ts

Italian translation in progress

Italian translation in progress

---

companion/src/modeledit/customfunctions.cpp
companion/src/modeledit/customfunctions.h

Companion: Time format for Special Functions Set Timers

---

companion/src/firmwares/opentx/opentxinterface.cpp

I think this is a typing error.

Typo correction

---

companion/src/cmake/FindXsd.cmake

Same fix done on master branch.
File format (line ending) was mixed, change to UNIX.

Fix #2138 on next branch

---

companion/src/modeledit/setup.cpp

Same fix done on master branch.

Fix #2122 on next branch

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.ui

Hello, is this the right place/branch for this?  I don't really use the "next" branch.  LMK if there's a better way.
Anyway, this just adds a bunch more telemetry values that can be sent to the simulator (F4 feature in Sim GUI).  Can use hex notation for values, and blanks are now skipped instead of sending zero value.
Cheers, 
-Max

Companion/Sim: Add more fields to telemetry simulator UI

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.ui

Same as #2171 but for 'next' branch.
Thanks!
-Max

Companion/Sim: [next] Add more fields to telemetry simulator UI

---

companion/src/modeledit/customfunctions.cpp

Fix for special function play icon Issue 2090

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h
companion/src/translations/companion_cs.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts

Fixes #1863, and a small bug when you select some axis to zoom and them deselect. It won go back to zooming both axis after deselecting x and y.

Fix for #1863

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h
companion/src/translations/companion_cs.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts

Well, progress on performance issue on next going slowly (short on time :wink:). So ported the changes from master to next.

log viewer #1863 for next

---

radio/src/targets/stock/lcd_driver.cpp

common replacement LCD needs different init data

Add support for LCD ERC12864FSF

---

companion/src/logsdialog.cpp

[companion][log viewer]fix fly session selection

---

companion/src/logsdialog.cpp

Add missing tr() in logsDialog.cpp on next.

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h

Performance is now the same, with or without selection.
Removed some unused stuff too.

[companion][log viewer]fix performance decrease if selection (fixes #2199)

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

Translation to PL is now up to date including fixing missing variables in pl.h.txt.

a lot of new translation and fixes

---

radio/src/translations/pl.h.txt

Small fixes

---

companion/src/appdata.cpp
companion/src/appdata.h
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/generaledit/generaledit.cpp
companion/src/generaledit/generalsetup.cpp
companion/src/generaledit/generalsetup.h
companion/src/generaledit/generalsetup.ui

Same additions from master but in next.

Add Battery Meter Range on Companion

---

companion/src/logsdialog.cpp

When back-porting logsdialog improvements to master @projectkk2glider found a bug, this is the fix on next!

Fix bug found by @projectkk2glider

---

radio/src/thirdparty/STM32_USB-Host-Device_Lib_V2.1.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_scsi.c

Same as #2237 but for `next`. I haven't tested this on the radio at all, just verified that it compiles!
Closes #2154

Fixes #2154: USB mass storage problem with cards bigger than 4GB

---

companion/src/simulation/myqdial.h
companion/src/simulation/simulatordialog-9x.ui
companion/src/simulation/simulatordialog-taranis.ui

Reset pots to the middle by right double clicking them

---

companion/src/appdata.cpp
companion/src/appdata.h
companion/src/apppreferencesdialog.cpp
companion/src/apppreferencesdialog.h
companion/src/apppreferencesdialog.ui
companion/src/mainwindow.cpp
companion/src/mainwindow.h
companion/src/mdichild.cpp

Profile backup path if set overrides general one, in any case the backup will be performed if either profile specific setting or general settings ones are enabled.
Disabling backup in profile will not disable backups if generic settings are enabled

Implement profile specific settings for backup folder.

---

companion/src/translations/companion_it.ts

Missing strings, they are also missing in other languages.
I also manually launched lupdate with -no-obsolete to clean up the file from obsolete no longer used strings.

Italian translations updated and obsolete removed.

---

companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/modeledit/setup.cpp
companion/src/modeledit/setup.h
companion/src/modeledit/setup_module.ui
radio/src/gui/9X/menu_model_setup.cpp
radio/src/myeeprom.h
radio/src/targets/sky9x/pulses_driver.cpp
radio/src/translations.cpp
radio/src/translations.h
radio/src/translations/cz.h.txt
radio/src/translations/de.h.txt
radio/src/translations/en.h.txt
radio/src/translations/es.h.txt
radio/src/translations/fi.h.txt
radio/src/translations/fr.h.txt
radio/src/translations/it.h.txt
radio/src/translations/pl.h.txt
radio/src/translations/pt.h.txt
radio/src/translations/se.h.txt

This is an attempt to fix #2239.
@bsongis I want you to tell me if I am going in the right direction. I've first tried to add opendrain option to the existing line for PPM parameters (length, pause, polarity) but there isn't enough space. I find working with menus very hard! The MENU_TAB is very hard to read/edit.
When this is completed I will rebase and squash commits to make it into one commit.

Projectkk2glider/issue 2239 ppm pushpull  for 9xrpro

---

radio/src/simu.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h
radio/src/tests/gtests.cpp

Simulator (and thus also gtests) follow-up to inversion of switches' polarity introduced in MEGA2650 by @JivaroFAD (55a7fba)

Fixes #2250

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/opentx/open9xGruvin9xeeprom.cpp
companion/src/firmwares/opentx/open9xSky9xeeprom.cpp
companion/src/firmwares/opentx/open9xStockeeprom.cpp
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/modeledit/customfunctions.cpp
companion/src/modeledit/setup.cpp
companion/src/wizarddata.cpp
radio/src/gui/9X/menu_model_setup.cpp
radio/src/gui/Taranis/menu_model_setup.cpp
radio/src/lua_api.cpp
radio/src/myeeprom.h
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/pulses/dsm2_arm.cpp
radio/src/pulses/pulses_avr.cpp
radio/src/pulses/pxx_arm.cpp
radio/src/tests/lua.cpp

Also provides a lua function to retrieve module settings

Fixes #2186

---

radio/src/lua.cpp

This should fix the problem described in https://github.com/opentx/opentx/issues/2084#issuecomment-102593774

Fixes #2084: wrong constant used to limit maximum number of expos

---

radio/src/Makefile
radio/src/buzzer.h
radio/src/gui/9X/menu_general_setup.cpp
radio/src/opentx.h
radio/src/vario.cpp

Useful during OpenTX hacknights ;-)

Support totally silent build (BUZZER=NO && AUDIO=NO)

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h
companion/src/qcustomplot/changelog.txt
companion/src/qcustomplot/qcustomplot.cpp
companion/src/qcustomplot/qcustomplot.h

Please have a look at the results, the screen is getting quite cluttered I think.

should solve #2267

---

companion/src/logsdialog.cpp
companion/src/logsdialog.h
companion/src/qcustomplot/changelog.txt
companion/src/qcustomplot/qcustomplot.cpp
companion/src/qcustomplot/qcustomplot.h

Just the same on next branch, as Log Viewer is exactly the same in next and master... ;)

log viewer enhancement, now for next

---

radio/src/targets/simu/simpgmspace.cpp

Fixes #2301: findTrueFileName() was not finding any files on Windows

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

Translation fixes

---

radio/src/Makefile
radio/src/gui/Taranis/menu_model_setup.cpp
radio/src/myeeprom.h
radio/src/opentx.cpp
radio/src/translations/de.h.txt

Only D16 mode is EU-compatible. This version will hide both D8 and LR12 modes.

Special EU firmware for Taranis

---

radio/src/functions.cpp

The functions were never disabled!

Dangerous module functions fix

---

companion/releasenotes.txt
companion/src/logsdialog.cpp
companion/src/logsdialog.h

Added session duration information in Log Viewer

---

radio/src/gui/Taranis/menus.h
radio/src/keys.h

Fixes #2444: Wrong scroll direction in simulators for X9E

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

Hot Fixes translation for 2.1.x

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

Adds new translations, some letter and words fixes

---

companion/src/translations/companion_pl.ts

Comapnion translation fixes

---

companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/modeledit/telemetry.cpp
companion/src/modeledit/telemetry.h
companion/src/modeledit/telemetry.ui
companion/src/shared/autocheckbox.h
radio/src/gui/Taranis/menu_model_telemetry.cpp
radio/src/myeeprom.h
radio/src/telemetry/telemetry.cpp

We have many wrong sensors, including openXsensor. 
The first ID is stored in EEPROM, but not used during the search loop

#2538 - Proposal for a fix. 

---

radio/releasenotes.txt
radio/src/gui/Taranis/lcd.cpp
radio/src/myeeprom.h

Fixes #2581: symbols for renamed physical inputs were missing

---

companion/src/translations/companion_pl.ts

new strings translation

---

radio/src/translations/it.h.txt

Fix FW Italian Translation

---

companion/src/simulation/simulatorinterface.cpp

Closes #2549 (*added by @projectkk2glider*)

Fixes #2549 - Use PrefixPath to find the simulator libs

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

New lines translation

---

radio/src/telemetry/frsky_d.cpp
radio/src/telemetry/frsky_sport.cpp

Fixes #2652:  Add missing presets to frskyDSetDefault()

---

radio/releasenotes.txt
radio/src/logs.cpp

Closes #2638
Not pretty but it works (tested in simu).

Fixes #2638: header line for logs fixed for 9XE

---

companion/src/CMakeLists.txt
companion/src/firmwares/opentx/simulator/CMakeLists.txt

The manual copy of SDL should not be needed anymore

Fixes #2678

---

companion/src/translations/companion_pl.ts

companion translation fix

---

radio/src/translations/it.h.txt

some fix for Italian translations
Please check it thoroughly before merge

Some Fix for it.h.txt

---

companion/src/translations/companion_pl.ts

Companioen pl translation fixes

---

radio/src/translations/tts_pl.cpp

Sound gramar fixes

---

radio/src/loadboot.cpp
radio/src/targets/taranis/pwr_driver.c

Fixes #2790: power on/off lop if big VCC capcitor was used

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/er9x/er9xinterface.cpp
companion/src/firmwares/er9x/er9xinterface.h
companion/src/firmwares/ersky9x/ersky9xinterface.cpp
companion/src/firmwares/ersky9x/ersky9xinterface.h
companion/src/firmwares/gruvin9x/gruvin9xinterface.cpp
companion/src/firmwares/gruvin9x/gruvin9xinterface.h
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/firmwares/opentx/opentxinterface.h
companion/src/firmwares/th9x/th9xinterface.cpp
companion/src/firmwares/th9x/th9xinterface.h
companion/src/mdichild.cpp
companion/src/mdichild.h

after #2763 and #2766, here it's again... :wink:
I will focus on the two issues at hand, the part of the cout's I'll do later, after finishing this one.
It still needs a lot of changes on the existing code but the new part is done! For a taranis eeprom it's working already.
What do you think of this solution?

for review: proposed solution for #2620 and #2778

---

radio/src/lua_api.cpp

This provides lua access to latitude and longitude in decimal degree format.
Snippet of lua code demonstrating usage"
```lua
local function init()
gpsId = getTelemetryId("GPS")
end
local function background()
gpsLatLon = getValue(gpsId)
if (type(gpsLatLon) == "table") then
-- fields gpsLatLon["Lat"] and gpsLatLon["Lon"] contain valid position data in decimal degrees
end
end
```
Code has been tested in companion21 and on Taranis hardware using both FrSky and Altis GPS hardware.

fix for issue 2758 lua support for latitude and longitude

---

companion/releasenotes.txt
companion/src/modeledit/mixes.cpp
companion/src/modelprinter.cpp
companion/src/modelprinter.h
companion/src/multimodelprinter.cpp

Fixes #2808: Mixes multiplex representation now the same as on the radio

---

radio/src/translations/tts_pl.cpp

Fix gramar error on thousands

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

Fixes in traslations

---

radio/src/translations/de.h.txt

only some strings changed for
X9D X9E 9XR-pro

update German openTx for V2.1.4  at 12.09.2015

---

radio/src/gui/menu_model.cpp

Fixes #2187.
Again, review with care and point me in the right direction.

Alert about duplicated receiver id on copy. #2187

---

companion/src/translations/companion_pl.ts

Keeping translation clean and up to date

---

radio/src/Makefile
radio/src/myeeprom.h
radio/util/commit-tests.sh

Closes #2950
Please check my changes in myeeprom.h carefully!

Fixes #2950: Mavlink build option was not working

---

radio/util/tts.py

Closes #2912.
If accepted, I will also update 2.0 branch, which has the same issue.

Fixes #2912: added missing "midtrim" and "endtrim" to FR

---

companion/src/translations/companion_pl.ts
radio/src/translations/tts_pl.cpp

1. Translation up to date. 2. Fixes in sound grammar file - time values

---

companion/src/translations/companion_pl.ts

 Translation up to date

---

radio/src/telemetry/telemetry.cpp

Haven't tested it, so please give it a quick look before merging.
Closes #3059

Fixes #3059: added unit conversions from km/h

---

companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/channels.cpp
companion/src/modeledit/channels.h
companion/src/modeledit/customfunctions.cpp
companion/src/modeledit/customfunctions.h
companion/src/modeledit/logicalswitches.cpp

Use new TableLayout for Logical switches, Outputs and Special functions

---

radio/src/gui/Taranis/view_telemetry.cpp
radio/src/lua/api_general.cpp
radio/src/main_arm.cpp

I managed to do Taranis only. The Horus will have to wait.

Re #2469: part2: keys accesible to Lua telemetry scripts (Taranis only)

---

companion/src/firmwares/er9x/simulator/er9xsimulator.h
companion/src/firmwares/ersky9x/simulator/ersky9xsimulator.h
companion/src/firmwares/opentx/simulator/opentxsimulator.cpp
companion/src/firmwares/opentx/simulator/opentxsimulator.h
companion/src/simulation/simulatordialog-horus.ui
companion/src/simulation/simulatordialog-taranis.ui
companion/src/simulation/simulatordialoghorus.cpp
companion/src/simulation/simulatordialogtaranis.cpp
companion/src/simulation/simulatorinterface.h
companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/telemetrysimu.ui

Tested on both Taranis (looks OK) and Horus simulators (GPS issue - assumed not related to telemetry simulator) in companion.

Ported simulator enhancements to next

---

companion/src/translations/companion_pl.ts
radio/src/translations/pl.h.txt

PL Translation fixes

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/telemetrysimu.ui

Fixes #3147 - Changes to send ASpd as knots

Changes to send ASpd as knots

---

companion/src/firmwares/er9x/simulator/er9xsimulator.h
companion/src/firmwares/ersky9x/simulator/ersky9xsimulator.h
companion/src/firmwares/opentx/simulator/opentxsimulator.cpp
companion/src/firmwares/opentx/simulator/opentxsimulator.h
companion/src/simulation/simulatorinterface.h
companion/src/simulation/telemetrysimu.cpp

Fixes #3207: proper sensor instance generation in Telemetry Simulator

---

radio/src/translations/se.h.txt

A new try with updated se translation.

Updated se translation and now in sync with en translation 3113

---

companion/src/translations/companion_pl.ts

New things and fixes

---

companion/src/appdata.cpp
companion/src/appdata.h
companion/src/generaledit/generaledit.cpp

And fix missing slider calibration.

Store control types and names in profile (fix #3260)

---

radio/src/targets/taranis/board_taranis.cpp
radio/src/targets/taranis/usbd_conf.h
radio/src/targets/taranis/usbd_hid_joystick.c

Had basically already done it when looking at it, so...
OK on Windows, maybe someone can test on linux?

Joystick now supports 24 buttons (ch9-32) (fix #3268)

---

radio/src/translations/it.h.txt

Fix it.h.txt

---

radio/src/CMakeLists.txt
radio/src/cli.cpp
radio/src/disk_cache.cpp
radio/src/disk_cache.h
radio/src/gui/horus/view_statistics.cpp
radio/src/opentx.h
radio/src/sdcard.cpp
radio/src/targets/horus/board_horus.h
radio/src/targets/horus/diskio.cpp
radio/src/targets/simu/CMakeLists.txt
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h
radio/src/thirdparty/FatFs/diskio.h
radio/src/thirdparty/FatFs/ff.h

* SIMU_DISKIO option available again
* new option DISK_CACHE defaults to ON for Horus
* printf("%f") fixed in CLI
Closes #3374

Fixes #3374: added SD card disk cache for Horus

---

companion/src/modeledit/flightmodes.cpp
companion/src/modeledit/flightmodes.h

Plus a minor fix for Fade In edit finished which did not flag modified.
Only compiled and tested on Ubuntu 14.04

Fixes #3214: Flight mode clear

---

radio/sdcard/horus/WIDGETS/BattCheck/main.lua

Add widget not configured management
Widget size 1/2 now available also

Widget update

---

radio/sdcard/horus/WIDGETS/BattCheck/main.lua

It seem to have no interaction with the rest of the system, albeit issue reports where neither very precise or reproductible

Use only CUSTOM_COLOR, 

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h
companion/src/simulation/telemetrysimu.ui

It seemed to be missing. I have still no clue why this sensor is supposed to be sent as 0.01ml. Is there any sensor in this world capable to measure that? Should it be changed as well to something more reasonable? (ml is just enough, IMHO)

#3505: add fuel quantity sensor in telemetry simulator

---

radio/src/gui/9x/lcd.h
radio/src/gui/9x/splash.cpp
radio/src/main_avr.cpp
radio/src/targets/9x/lcd_ks108_driver.cpp
radio/src/targets/mega2560/board_mega2560.cpp
radio/src/targets/mega2560/board_mega2560.h

+little option (not defined) to reduce encoder resolution (please keep it)

[MEGA2560] KS108+ Voice+Splash "far" (Voice driver,KS108 and ST7920 tested OK)

---

companion/src/CMakeLists.txt
radio/src/gui/horus/widgets/outputs.cpp

Taranis like channel monitor for Horus. Unlike the LUA version this one shows actuel channel output, not the mixer output. Maybe the LUA one should be remove if this gets merged into next.

Native channel monitor widget

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/modeledit/flightmodes.cpp
radio/src/opentx.cpp

Ref #3473 
Created a new branch to resolve conflicts in the port from master. Hope that is okay.

Fixes 3473 port to next

---

radio/src/gui/horus/menu_model_mixes.cpp
radio/src/gui/horus/themes/darkblue.cpp
radio/src/gui/horus/themes/default.cpp

Optimize code a little
Fix colors for the new bitmap

Fix colors on the new slowdelay bitmap

---

radio/sdcard/horus/WIDGETS/Counter/main.lua

If not, it gnerates lua errors when not displayed. it can be empty, but since we have one, let's keep it counting !
Thx Noircogi for spotting this one

update function is required

---

radio/util/Dockerfile

- Add companion compile capability to the docker image

One docker to rule them all !

---

radio/src/simu.cpp
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/sky9x/i2c_driver.cpp
radio/src/targets/sky9x/rtc_ds3231_driver.cpp
radio/util/commit-tests.sh

Note that simu still crashes on startup in the readRtc function

Fix AR9X build and add it to regular commit tests.

---

radio/src/gui/480x272/view_text.cpp

The // where added Jan25 as part of https://github.com/opentx/opentx/commit/5c71d74aabcafc0c8874de5970ae5c654ba5d9c1#diff-e7a8e42860fdbdf14bb250f27536fde6

Fix compilation warning on Horus.

---

radio/src/CMakeLists.txt
radio/src/main_avr.cpp
radio/src/storage/eeprom_common.cpp
radio/src/storage/eeprom_raw.cpp
radio/src/storage/eeprom_rlc.cpp
radio/src/storage/eeprom_rlc.h
radio/src/targets/9x/CMakeLists.txt
radio/src/targets/9x/board.h
radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp
radio/src/targets/common/avr/CMakeLists.txt
radio/src/targets/common/avr/board_avr.h
radio/src/targets/common/avr/eeprom_driver.cpp
radio/src/targets/gruvin9x/board.cpp
radio/src/targets/gruvin9x/board.h
radio/src/targets/mega2560/board.h
radio/src/targets/simu/CMakeLists.txt
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h
radio/src/targets/simu/simueeprom.cpp
radio/src/targets/sky9x/CMakeLists.txt
radio/src/targets/sky9x/board.h
radio/src/targets/sky9x/eeprom_driver.cpp
radio/src/targets/taranis/board.h
radio/src/targets/taranis/bootloader/boot.cpp
radio/src/targets/taranis/i2c_driver.cpp
radio/src/tests/CMakeLists.txt
radio/src/tests/eeprom.cpp

EEPROM simplification

---

radio/src/pulses/dsm2_arm.cpp
radio/src/pulses/multi_arm.cpp

We send an extra stopbit and the logic for driving the transistor was swapped. Thanks Mike for noticing (http://www.rcgroups.com/forums/showpost.php?p=35671709&postcount=5151)

Fix timing of Multi and DSM2 protocol

---

radio/src/gui/480x272/radio_hardware.cpp

Fix column handling

---

radio/src/lua/api_general.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h

Also introduce new event to lua;
EVT_ROT_BREAK
EVT_ROT_LONG
EVT_ROT_LEFT
EVT_ROT_RIGHT

Move lua evt param from signed uint8_t to unsigned event_t

---

.travis.yml
radio/src/audio_arm.cpp
radio/src/audio_arm.h
radio/src/debug.cpp
radio/src/debug.h
radio/src/opentx.cpp
radio/src/tests/mixer.cpp
radio/src/tests/switches.cpp
tools/commit-tests.sh

* Switches audio filenames were wrong [Horus]
* sdAvailableLogicalSwitchAudioFiles was too small (we now have 64 LSW), fixed with BitFiled class

Audio fixes

---

companion/src/modeledit/mixerslist.cpp
companion/src/modeledit/mixerslist.h
companion/src/modeledit/mixes.cpp

Fixes Shift Drag n Drop (Move)
Only tested on Ubuntu 14.04
Will do another PR for Inputs which has same bug.

Fixes 3474 Mix line drag n drop before CH1

---

companion/src/modeledit/mixerslist.cpp
companion/src/modeledit/mixerslist.h
companion/src/modeledit/mixes.cpp

Port to next work by Elecpower: https://github.com/opentx/opentx/pull/3838

Companion bugfix

---

companion/src/modeledit/heli.cpp
companion/src/modeledit/inputs.cpp

Fixes 3662 Companion missing "none" setting for heli sources 
Fixes Inputs Drag n Drop 
Fixed #3662

Port fixes by elecpower to next

---

companion/src/modeledit/heli.cpp

Fixes #3662 Companion missing "none" setting for heli sources

Fixes 3662 Companion missing "none" setting for heli sources

---

radio/src/gui/480x272/model_outputs.cpp

Listed bug was also affecting copy sticks/tri…ms to subtrims
Fix #3870

Fix indexing in outputs 

---

radio/src/opentx.cpp
radio/src/opentx.h
radio/src/switches.cpp
radio/src/targets/simu/simpgmspace.h

This ~~might~~(https://github.com/opentx/opentx/issues/3827#issuecomment-252425167) also fix the #3827 original issue.

Re #3827: added mutex to getADC(), because adcRead() is not reentrant

---

radio/sdcard/horus/S6R/S6R.lua
radio/sdcard/taranis/S6R_Calibrate/S6R_Calibrate.lua

Need somebody to check that please.
This fixes #3905

Use a less controversial wording + performance fixes.

---

radio/src/gui/480x272/view_main.cpp

Prevent segfault on extended trim

---

radio/src/functions.cpp
radio/src/tests/functions.cpp

Fixes #3858: added edge detection to RESET and GVAR INC/DEC functions

---

radio/src/opentx.cpp

Add failsafe check to Horus

---

radio/src/audio_arm.cpp
radio/src/audio_arm.h
radio/src/cli.cpp
radio/src/debug.cpp
radio/src/debug.h
radio/src/functions.cpp
radio/src/targets/horus/audio_driver.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/sky9x/audio_driver.cpp
radio/src/targets/sky9x/audio_driver.h
radio/src/targets/taranis/audio_driver.cpp
radio/src/targets/taranis/board.h

Should improve (or even fix) #3815  and #1838.

Re #3815: Audio refactoring

---

companion/src/modeledit/curves.cpp
companion/src/modeledit/curves.ui

Addresses the requests raised in #2998.
For consideration

Companion model edit curves tab enhancement

---

companion/src/modeledit/curves.cpp
companion/src/modeledit/curves.ui

Port #3933 to next

---

radio/src/gui/212x64/model_mixes.cpp

Fix column alignment between text/digits

---

radio/src/translations/tts_de.cpp
radio/util/tts_de.py

Spoken numbers fixed:
100 -> "ein", "hundert"
1000 -> "ein", "tausend"
999 -> "9", "hundert", "99"
Timers:
60 seconds -> "eine", "minute"
3600 seconds -> "eine", "stunde"
120 seconds -> "2", "minuten"
Sound files needed to be generated because new words are used.

German spoken language fixed.

---

radio/src/gui/480x272/model_mixes.cpp

Add bottom mixer status bar when editing mixer

---

radio/src/translations/nl.h.txt

Translated 3 English lines into Dutch

Added translation for expected version and delete error

---

radio/src/lua/api_general.cpp

[LUA] added docs for telemetry push/pop functions

---

radio/src/cli.cpp
radio/src/debug.cpp
radio/src/debug.h
radio/src/main_arm.cpp
radio/src/targets/horus/CMakeLists.txt
radio/src/targets/horus/bluetooth_driver.cpp
radio/src/targets/horus/board.cpp
radio/src/targets/horus/board.h
radio/src/targets/horus/hal.h
radio/src/telemetry/frsky.cpp

Bluetooth driver added to Horus, BT_EN_GPIO_PIN was wrong on beta board

---

radio/src/translations/de.h.txt

Telemetry unit translation seem of (not sure why that would be the case)
This fixes #4031

Fix german units

---

radio/src/gui/common/stdlcd/model_mixes.cpp

Revise column for mixer

---

companion/src/storage/mountlist.cpp
radio/src/targets/simu/simpgmspace.cpp

Includes fixes from #4049 and #4050.

Fix build on FreeBSD

---

radio/src/gui/128x64/widgets.cpp
radio/src/gui/212x64/gui.h
radio/src/gui/212x64/model_outputs.cpp
radio/src/gui/212x64/widgets.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp
radio/src/gui/common/stdlcd/widgets.cpp

Needs more tests before being merged

[X7D/X9E] GVars display fixed (menus INPUTS / MIXES / OUTPUTS)

---

radio/src/gui/480x272/widgets/outputs.cpp

Fix two column handling

---

radio/src/gui/480x272/model_select.cpp
radio/src/storage/modelslist.h

Gain a couple of pixel here and there to allow both longest cat and model to be displayed

Fine tune model select screen

---

companion/src/apppreferencesdialog.cpp
companion/src/customizesplashdialog.cpp
companion/src/helpers.cpp

Fix Issue 4057 Correct fix to support X9E also as suggested by @kilrah

Fix Issue 4057 for X9E also.

---

radio/src/telemetry/spektrum.cpp
radio/src/translations/cz.h.txt
radio/src/translations/de.h.txt
radio/src/translations/en.h.txt
radio/src/translations/es.h.txt
radio/src/translations/fi.h.txt
radio/src/translations/fr.h.txt
radio/src/translations/it.h.txt
radio/src/translations/nl.h.txt
radio/src/translations/pl.h.txt
radio/src/translations/pt.h.txt
radio/src/translations/se.h.txt

Small update to Spektrum parsing code.

Add new sensors for Spektrum’s Serial Telemetry Receiver (SPM4649T)

---

companion/src/CMakeLists.txt
companion/src/constants.h
companion/src/helpers.cpp
companion/src/mainwindow.cpp
companion/src/mdichild.cpp
companion/src/simulator.cpp
radio/src/gui/common/stdlcd/popups.cpp

Temporary to allow nightly as discussed

Prep for Nightly

---

companion/src/modeledit/modeledit.cpp
companion/src/simulator.cpp

Fix tricky access to Horus settings

---

companion/src/CMakeLists.txt
companion/src/companion.cpp
companion/src/simulator.cpp
companion/targets/mac/MacOSXBundleInfo.plist.in

Tested by @kilrah  and @3djc and it seems to improve things.
One "downside" is that more will receive correct scaling and #3135 will be more urgent to fix.

Enable hide according to http://doc.qt.io/qt-5/highdpi.html

---

companion/src/firmwares/opentx/opentxinterface.cpp

Fix for QT53

---

radio/sdcard/taranis/SCRIPTS/WIZARD/delta.lua
radio/sdcard/taranis/SCRIPTS/WIZARD/multi.lua
radio/sdcard/taranis/SCRIPTS/WIZARD/plane.lua
radio/sdcard/taranis/SCRIPTS/WIZARD/wizard.lua

Fix ROT encoder nav for wizards

---

radio/sdcard/horus/SCRIPTS/WIZARD/plane/wizard.lua

This Fixes #4111 
I have updated sdcard-horus-2.2V0004.zip accordingly on http://downloads.open-tx.org/2.2/nightly/sdcard/

Fix #4111 and fix capitalize issue

---

companion/src/modeledit/customfunctions.cpp

Port #4116 to Next

---

radio/src/gui/212x64/model_select.cpp

Fix copy and move not happening on X9E

---

radio/src/CMakeLists.txt
radio/src/targets/taranis/bootloader/boot.cpp

Better handling of X7 bootloader screen

X7 bootloader improvement

---

tools/nightly22/build-sdcard.sh

Somewhat untested, will be during next nightlie :D

Add X7 sdcard pack generation for nightlies22

---

radio/src/gui/212x64/model_select.cpp
radio/src/gui/480x272/model_select.cpp
radio/src/storage/modelslist.h

Deletion confirm changed from filename to modelname
Fixes also Taranis that was not displaying model name
This fixes #4098

Deletion confirm changed from filename to modelname(filename)

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/480x272/layout.h
radio/src/gui/480x272/lcd.cpp
radio/src/gui/480x272/lcd.h
radio/src/opentx.cpp
radio/src/targets/horus/diskio.cpp
radio/src/targets/taranis/diskio.cpp

Minor syntax errors and compiler warnings.

Minor build fixes

---

companion/src/simulation/simulatordialog.cpp
radio/src/simu.cpp

A couple of proposal fixes:
- Add keys for rotary control (comma, period)
- Fix for wheelEvent function

Horus simulator rotary control improvements 4085

---

radio/src/gui/480x272/bitmapbuffer.h

Add handling of negative width to drawSolidFilledRect

---

companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/modeledit/telemetry_sensor.ui

Companion was not updated when mWatt and Rad where added
This fixes #4174

Add missing units

---

companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/channels.cpp
companion/src/modeledit/channels.h
companion/src/shared/genericpanel.h

Fixes #4153 Companion Outputs - not all field changes triggering save prompt

Fixes #4153: Companion Outputs alts to sub trim, min and max not prompting to save

---

companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/mixes.cpp
companion/src/modeledit/setup.cpp
companion/src/process_flash.cpp

Small stuff, hopefully nothing too controversial here.  :)  This fixes all MSVC warnings I could find (w/out going to /W4).

[companion] Fix a few reasonable warnings brought up by MSVC /W3.

---

companion/src/translations/companion_cn.ts

#4179 cn translation done

---

radio/src/gui/128x64/model_logical_switches.cpp
radio/src/gui/128x64/model_outputs.cpp
radio/src/translations/cz.h.txt
radio/src/translations/de.h.txt
radio/src/translations/en.h.txt
radio/src/translations/es.h.txt
radio/src/translations/fi.h.txt
radio/src/translations/fr.h.txt
radio/src/translations/it.h.txt
radio/src/translations/nl.h.txt
radio/src/translations/pl.h.txt
radio/src/translations/pt.h.txt
radio/src/translations/se.h.txt

Allow autoswitch for LS AND switch
Add POPUPMENU base edit/clear/copy/paste to LS screen
Add POPUPMENU to OUTPUTS screen for reset/trim->subtrim/stick->subtrim

X7-improvement

---

radio/src/io/frsky_sport.cpp
radio/src/targets/horus/board.cpp
radio/src/targets/horus/board.h
radio/src/targets/horus/telemetry_driver.cpp
radio/src/targets/sky9x/board.h
radio/src/targets/sky9x/telemetry_driver.cpp
radio/src/targets/taranis/board.h
radio/src/targets/taranis/telemetry_driver.cpp
radio/src/telemetry/telemetry.cpp
radio/src/telemetry/telemetry.h

Not tested at all, would need test on both Horus and Taranis

[Horus] Fixes #4205

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/128x64/model_telemetry.cpp

This fixes curves selections and  name display on X7

fix curves on X7

---

companion/src/translations/companion_zh.ts

Chinese translation minor revise, maily on Telemetrysimulator page

Chinese translation minor revise

---

companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/channels.cpp
companion/src/modeledit/channels.h
companion/src/shared/genericpanel.h

Port #4189 to next for adding data modification for sub trim, min and max on model edit outputs

Port #4189 to next

---

companion/src/firmwares/opentx/opentxinterface.cpp

Review based on Horus and X7 capabilities

getCapability review

---

companion/src/firmwares/opentx/opentxeeprom.h
companion/src/firmwares/opentx/opentxinterface.cpp
radio/src/sdcard.h
radio/src/storage/eeprom_rlc.cpp
radio/src/targets/taranis/CMakeLists.txt

[X7] EEPROM Variant introduced for Companion import

---

companion/src/multimodelprinter.cpp

A "somewhat" non critical issue, but nonetheless :D

Do not use color coded RSSI alarms on Taranis/Horus prints

---

radio/src/telemetry/frsky.h

(according to SPORT specification V3.4.0)

DIY ID range changed to 0x5100 - 0x52FF 

---

companion/src/mainwindow.cpp
companion/src/progressdialog.cpp
companion/src/progressdialog.h
companion/src/progresswidget.cpp
companion/src/progresswidget.h
companion/src/radiointerface.cpp

* show errors
* close dialog in nothing in progress widget

Fixes for "Read Models and Settings from the radio"

---

companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/modeledit/expodialog.cpp

Fixes #4290: Input Offset fix [Horus]

---

companion/src/CMakeLists.txt
companion/src/apppreferencesdialog.h
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxeeprom.cpp
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/mdichild.cpp
companion/src/modelslist.cpp
companion/src/modelslist.h
companion/src/radiodata.cpp
companion/src/storage/categorized.cpp
companion/src/storage/otx.cpp

This is a proposal to fix #4295

Proposition : model number handling

---

radio/src/gui/128x64/model_flightmodes.cpp

- display more info on ALL screen
- allow trim settings on FM0 One screen
NEEDS TESTING

Rework X7 flight mode screen

---

companion/src/flasheepromdialog.cpp
companion/src/flasheepromdialog.h
companion/src/mainwindow.cpp
companion/src/radiointerface.cpp

* radio not found was show behind all windows (missing parent)
* bad behavior on write when radio not found
Do not merge yet, I will do some more checking and fixing.

Read/write backup fixes:

---

radio/src/lua/api_lcd.cpp

Update doc for functions not available on X7

---

companion/src/firmwares/opentx/opentxinterface.cpp

Fix fields name (mixer,GC,..)

---

companion/src/translations/companion_zh.ts

Chineses fonts width of ubuntu is differents from windows, layout ( words align ) re-modified for windows version, considering most people use windows version

Chinese translation update for better alignment

---

radio/src/lua/widgets.cpp

This addresses the comment https://github.com/opentx/opentx/issues/3882#issuecomment-252257264 . I decided not to change the order of options.
Closes #3882

Re #3882: parse theme/widget options depending on option type

---

radio/src/gui/128x64/view_telemetry.cpp
radio/src/gui/212x64/view_telemetry.cpp

and on x9 and x7 prevent unnecessary redraw of line

Fix missing line on X7 on telem screen

---

.gitignore

If these are present in a 2.2 OpenTX repo, they are remains from a
OpenTX 2.1 build

No longer ignore output files

---

radio/src/gui/128x64/view_main.cpp

Fine tune X7 trim display

---

radio/src/gui/128x64/view_telemetry.cpp

on ARM 128x64. Instead gracefully display a popup instead
Fix #4412

Do not reset telem on ENT push while in telem view

---

companion/src/translations/companion_fr.ts

Correction de fautes de grammaire et autres.

Corrected some typo.

---

companion/src/translations/companion_fr.ts

Je pense que c'est bon.
Je testerai tout comme il faut lorsque la RC11 sera sortie.

Type correction, again.... ;)

---

radio/src/gui/480x272/bitmapbuffer.h
radio/src/lua/api_lcd.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h
radio/src/lua/widgets.cpp
radio/src/main_arm.cpp
radio/src/targets/horus/board.h
radio/src/targets/taranis/board.h

Lua bitmap functions cleanup and docs update
Added x or y < 0 check to drawBitmap()
Closes #4284

Prevent Lua from allocating all heap memory (Horus)

---

radio/src/logs.cpp

Fix X7 sd logs

---

companion/src/firmwares/opentx/opentxinterface.cpp
radio/src/dataconstants.h
radio/src/gui/212x64/radio_hardware.cpp
radio/src/gui/480x272/radio_hardware.cpp
radio/src/opentx.cpp
radio/src/pulses/multi_arm.cpp
radio/src/pulses/pulses_arm.cpp
radio/src/targets/horus/board.h
radio/src/targets/horus/pulses_driver.cpp
radio/src/targets/sky9x/board.h
radio/src/targets/sky9x/pulses_driver.cpp
radio/src/targets/taranis/board.h
radio/src/targets/taranis/pulses_driver.cpp
radio/src/telemetry/telemetry.cpp
radio/src/telemetry/telemetry.h

Telemetry not working yet though, still something to debug

Multiprotocol working on sky9x

---

companion/src/wizarddata.cpp

Fix wrong witch selected for Horus wiz on companion
Fix wrong mixes (stick instead of inputs) for Horus wiz on companion
Thx André M for the report

Fix companion wizard behavior for Horus

---

radio/src/datastructs.h
radio/src/gui/128x64/model_custom_scripts.cpp
radio/src/gui/212x64/model_custom_scripts.cpp
radio/src/gui/480x272/model_custom_scripts.cpp
radio/src/lua/api_general.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h

Improved parsing of Lua mixer script inputs
Closes #4438

Fixes #4438: wrong cast used when setting Lua mixer script input source

---

radio/src/CMakeLists.txt
radio/src/audio_arm.cpp
radio/src/cli.cpp
radio/src/debug.h
radio/src/gui/480x272/bitmapbuffer.cpp
radio/src/lua/api_general.cpp
radio/src/thirdparty/Lua/src/lapi.c
radio/src/thirdparty/Lua/src/lauxlib.c
radio/src/thirdparty/Lua/src/ldo.c
radio/src/thirdparty/Lua/src/linit.c
radio/src/thirdparty/Lua/src/lmem.c
radio/src/thirdparty/Lua/src/lrotable.c
radio/src/thirdparty/Lua/src/lrotable.h
radio/src/thirdparty/Lua/src/luaconf.h
radio/src/thirdparty/Lua/src/lvm.c
radio/src/thirdparty/Stb/stb_image.h

This is the same as #4458 just squashed and rebased on latest next.

Lua: All usage of double converted to float

---

radio/src/gui/128x64/model_flightmodes.cpp

While it checks ok on sime and radio, please review thoroughly the changes
This fixes #4513

Fix FM screen on X7

---

companion/src/modeledit/expodialog.cpp
companion/src/modeledit/mixerdialog.cpp

Change text "not" to ! symbol to fix VS15 Build.  Fixes Issue 4522

Change text "not" to ! to fix VS15 Build Issue_4522

---

radio/sdcard/taranis-x9/SCRIPTS/WIZARD/wizard.lua

Remove Heli choice from model wiz as we do not have one

---

radio/src/gui/128x64/model_special_functions.cpp

Add popup menu to Play value SF on X7

---

radio/src/gui/480x272/widgets/modelbmp.cpp
radio/src/maths.cpp
radio/src/opentx.h

Quick fix ... comments welcome :)

[Horus] Fixes #3775

---

radio/src/gui/128x64/model_logical_switches.cpp

Casting fix

---

radio/src/io/frsky_sport.cpp
radio/src/telemetry/telemetry.cpp

Tested on X7 with IntModule=NONE and ExtModule=MULTI

Fixes #4478

---

radio/src/gui/128x64/view_telemetry.cpp

As per #4576 discussion and screenshots 
This fixes #4576

X7 review telem bars screen

---

radio/src/gui/480x272/widgets.cpp

Fine tune 6 pos dispay on main view

---

companion/src/translations/companion_fr.ts

I tried to make the sentences as small as possible, but French language is very verbose...

French translation for the new simulator

---

radio/src/sdcard.cpp

Filter out hidden and system files

---

tools/nightly22/build-nightly.sh

A possibly more logical sequence of event

Re-organize nightly sequence

---

radio/src/gvars.cpp

Handle neg gvars precision

---

radio/src/lua/api_lcd.cpp

Fixes #4608 
Compiled and tested the #4581 script on an X9D+

LUA horizontal and vertical lcd.drawLine(...) fix

---

companion/src/translations/companion_fr.ts

Updated French translation according the .tx file send to me by @3djc

French Translation

---

radio/src/gui/480x272/screens_setup.cpp

Fixes #3795

---

companion/src/companion.qrc
companion/src/images/simulator/icons/svg/line_horiz.svg
companion/src/themes/default/style.css

Could someone try this on a high-def display to make sure it scales properly?  TIA.
(closes #4638)

[Simulator] New skin for channel output indicators. 

---

companion/src/CMakeLists.txt
companion/src/companion.cpp
companion/src/simulator.cpp

The RCC takes "a while" (precious seconds! ;-) ) to re/build and it was repeating that for each of the two targets.  Funny thing with the variable name though, very strange (see comment @ 165).

[build] Only build companion/simulator resources files once.

---

radio/src/gui/128x64/model_logical_switches.cpp

Allow neg value for telem comparison fonctions

---

companion/src/eeprominterface.h
companion/src/simulation/radiooutputswidget.cpp

Use rouding like arm radios for channel outputs

---

companion/src/translations/companion_fr.ts

Easily updated French translation.
Thanks a lot to @mpaperno !! It is now so easy for translator. 💯 
See #4637

Updated French translation

---

companion/src/translations/companion_fr.ts

Added some tiny cosmetic changes in order to help user to make the connection between Companion and the radio menu.
This may (or not) be a good idea. I just got the idea because some recurrent questions/confusions on the French forum.
It is as you want to accept or not. 😄

Tiny French cosmetic changes

---

companion/src/modeledit/telemetry.cpp

Companion : fix vario for Horus

---

companion/src/mdichild.cpp
companion/src/modeledit/modeledit.cpp

Make default category translatable (with dev warning)

---

companion/src/multiprotocols.cpp
companion/src/translations/companion_de.ts

Small progress on German translations

---

companion/src/firmwares/opentx/opentxinterface.cpp

Companion : display warning on eeprom upgrade

---

companion/src/companion.qrc
companion/src/generaledit/calibration.cpp
companion/src/helpers.cpp
companion/src/images/simulator/icons/svg/folder_open.svg
companion/src/modelslist.cpp
companion/src/simulation/debugoutput.cpp
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatorstartupdialog.cpp
companion/src/simulator.cpp
radio/src/lua/api_general.cpp
radio/src/pulses/multi_arm.cpp
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h

A couple warnings, possible array array buffer overflow, and some "cosmetics."  And a deadlock issue... and a pear tree.

Minor misc. fixes

---

companion/src/translations/companion_fr.ts

Updated French translation once again... 😉

Updated French translation.

---

radio/src/gui/128x64/gui.h
radio/src/gui/128x64/model_special_functions.cpp
radio/src/gui/128x64/widgets.cpp

Please review thoroughly
This fixes #4744

X7 : Add GVAR handling similar to X9

---

radio/src/gui/128x64/model_logical_switches.cpp

Prevent delay to be accessible for edge LS

---

companion/src/translations/companion_fr.ts

Updated the French translation.
I got a doubt (see snapshot below), if the field `New model` can support or not foreign accent. There is no developer comment... For now, I didn't change it.

Updated FR translation for Companion 2.2.0N368

---

radio/src/gui/128x64/model_special_functions.cpp

3djc/fix #4795

---

companion/src/translations/companion_fr.ts

Translate last missing field + correct some translation (confirmation box) when deleting models/categories.

Updated few French translations on the N369

---

radio/src/targets/simu/opentxsimulator.cpp

@mpaperno you touched that function, can you approve or make a proper fix?

Fix key variable not initialised

---

radio/src/gui/480x272/view_channels.cpp

Invert outputs limits when output is reversed

---

radio/src/targets/sky9x/rtc_ds3231_driver.cpp

2nd try...
Fixes DS3231 RTC read/write on AR9X

Fix DS3231 RTC read/write on AR9X

---

radio/src/gui/128x64/navigation.cpp
radio/src/gui/128x64/radio_calibration.cpp

It does seem to do the job, but not overly happy with the fix
This fixes #4833

X7 : fix calibration interuption

---

companion/src/simulation/telemetrysimu.ui
radio/src/gui/128x64/radio_diaganas.cpp

Not tested on an actual radio but should be okay

Add RAS to X7 analogs screen

---

companion/src/translations/companion_fr.ts

Fix French translation

---

radio/src/gui/128x64/model_special_functions.cpp
radio/src/gui/212x64/model_special_functions.cpp
radio/src/gui/480x272/model_special_functions.cpp

Previous fix was very wrong, attempt to do a better one
Please review thoroughly,

Prevent telemetry in global functions

---

radio/src/gui/128x64/model_outputs_arm.cpp

This now also switch to PREC0 when displayed value reaches 100 in PPM_US
This fixes  #4864

X7 output main view : dynamic PREC also for PPM_US

---

companion/src/boards.cpp
companion/src/boards.h
companion/src/eeprominterface.cpp
companion/src/eeprominterface.h
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/generaledit/hardware.cpp
companion/src/generaledit/hardware.h
companion/src/helpers.cpp
companion/src/helpers.h
companion/src/modeledit/channels.cpp
companion/src/modeledit/customfunctions.cpp
companion/src/modeledit/logicalswitches.cpp
companion/src/modeledit/mixes.cpp
companion/src/modeledit/setup.cpp
companion/src/modelprinter.cpp
companion/src/modelprinter.h
companion/src/multimodelprinter.cpp
companion/src/radiodata.cpp
companion/src/radiodata.h

And only a little refactoring  ;-)  More changes on tap, based on these.

[Companion] Show custom channel, G-Var, and Curve names throughout UI.

---

companion/src/translations/companion_fr.ts

Fixed French translations

---

radio/src/gui/128x64/model_special_functions.cpp

Fix adjust GVAR and Volume

---

radio/src/targets/common/avr/CMakeLists.txt

Fixes opentx-9x-autoswitch-autosource-dblkeys-battgraph-telemetrez-sp22-stickrev-pgbar-en.hex
TELEMETREZ handling is done line 113

Fix server compile
